### PR TITLE
Fix compilation on eoan

### PR DESCRIPTION
**Pull request by jackpot51**
This should fix build failures on eoan

### CODE REVIEW

**Comment by jackpot51** [comment]
@brs17 Looks like this will need to become the master_eoan branch, as it fixes compilation there but fails to compile on 18.04

@cassidyjames I don't see a good way to compile on both 18.04 and 19.10 with the same codebase

**Comment by jackpot51** [comment]
A master_eoan branch has been created

**Comment by ricotz** [comment]
This change is wrong. Please follow https://github.com/ximion/appstream/pull/258

**Comment by ricotz** [comment]
Explicit casting would be an acceptable fix to undo the upstream API break.

**Comment by jackpot51** [comment]
@ricotz why is this change "wrong"? The new valac has stricter rules, the explicit casting I do here is just similating what was done on older valac.

**Comment by ricotz** [comment]
@jackpot51 I have read your patch wrong, and thought you were trying to follow the upstream change. You don't need to assign it to an extra local variable though.

**Comment by jackpot51** [comment]
Thanks for the clarification @ricotz

**Comment by ricotz** [comment]
@jackpot51 If you run into something like this then contact upstream and start to question such changes. So don't silently deal with it.

**Comment by jackpot51** [comment]
@ricotz that is exactly what I was going to do...

**Pull request closed without merging**
