### PR TITLE
Update danish translation

### PR DESCRIPTION
**Pull request by CodeBeats2**
Update of danish translation.

### CODE REVIEW

**Review by n3m0-22 — CHANGES_REQUESTED** [review]
~~This was forked from https://github.com/elementary/appcenter instead of https://github.com/pop-os/shop. You can submit a new PR forked from the correct repo and it should work.~~ Please disregard this comment.

**Comment by n3m0-22** [comment]
@CodeBeats2 This is not working due to the two different translations for the same `msgid` as noted above. I don't know which one you would preferred to keep. Please choose the correct one and delete the other. Once one of them has been removed this should work properly and be ready for approval. Thanks.

**Comment by CodeBeats2** [comment]
@n3m0-22 I dont know if anything has change. Tried updating the translation, where the issue maybe was. I am not used to github. I couldn't se what exactly you where referring to.

**Comment by n3m0-22** [comment]
Yes I see the change you made. That should solve the problem. I have already  pushed the new commit. Assuming it builds without error this time, I will test it as soon as it is ready.

**Review by n3m0-22 — APPROVED** [review]
This is working correctly now. The new translations are showing properly. All pop-shop testing passed. Thank you for your contribution to Pop!_OS.

**Review by 13r0ck — APPROVED** [review]

**Pull request merged**
