### PR TITLE
Disable XDG Autostart

### PR DESCRIPTION
**Pull request by isantop**
Since update checking is no-longer handled by Pop Shop and is instead taken care of by the updater, we no longer need to keep Pop Shop running in the background full-time. This removes the XDG autostart shortcut to prevent Pop Shop from automatically starting on log in. Shop can still be started manually, and will now only run when the window is open.

### CODE REVIEW

**Review by n3m0-22 — DISMISSED** [review]
Pop-Shop is no longer in xdg autostart. This is confirmed by restarting and `io.elementary.appcenter` not running. All testing passed.

[shop-xdg-test.txt](https://github.com/pop-os/shop/files/9617753/shop-xdg-test.txt)

**Comment by ids1024** [comment]
Pop!_Shop also provides a dbus service used as a search provider. I think this would break that? Though it's proven somewhat fragile already.

**Comment by isantop** [comment]
I've noticed that Pop Shop can occasionally consume very large amounts of CPU time and memory; I don't know if providing search for non-installed applications is worth causing this large amount of usage. 

I'll also note, anecdotally, that the dbus search provider only very rarely returns results relevant to a query (when it returns results at all). After testing just now, even with pop shop open and running, it fails to return any results in the applications search for the query "music" under "Available to Install"

**Comment by ids1024** [comment]
Yeah, testing Pop!_Shop results in https://github.com/pop-os/cosmic, I definitely saw that it has some issues. And given the memory usage issues, the tradeoff isn't clear.

**Review by mmstick — DISMISSED** [review]

**Review by 13r0ck — CHANGES_REQUESTED** [review]
Screenshot from 2022-09-26 10-57-50

@ids1024 is correct, Unfortunately this breaks the application library.

**Comment by reuvenpo** [comment]
This PR seems very relevant to issue #407 .
Is there anything that can be done to continue this work, or is it completely outdated by now?

**Comment by jacobgkau** [comment]
>  Is there anything that can be done to continue this work, or is it completely outdated by now?

This PR is stale, we'd need to redo the work against the current version of the Pop!_Shop (but would still need to either make it not break the dbus search service or decide if we actually want to remove that).

**Comment by reuvenpo** [comment]
Ah, that's out of my scope for sure...
But at least as a user, I think that it's worth investing a bit of time in. The shop takes up a lot of ram, which is an issue for a background application which isn't even doing much other than search suggestions...
If I can suggest anything, then I'd say that if you really want to keep the search service as it is today then it might be worth making a small background application just for that.

**Pull request closed without merging**
