### PR TITLE
Fix screen cropping behavior by reverting to upstream version

### PR DESCRIPTION
**Pull request by ids1024**
Issue described in https://github.com/pop-os/shop/pull/271#pullrequestreview-675262879

This matches the upstream version of the code. As far as I can tell `AppScreenshot` was never upstream. Not sure why it was added as a custom widget. But at present the upstream version seems to work better.

### CODE REVIEW

**Comment by cassidyjames** [comment]
I recall @isantop wrote that widget when working on making Pop!_Shop adaptable to smaller widths (e.g. for better tiling support). Any reasonable small screen adaptive improvements are of course welcome upstream as well so long as they don't negatively affect the layout or behavior at default sizes.

**Comment by ids1024** [comment]
Ah, right. I forgot `GtkImage`s can't shrink (Gtk4's `GtkPicture` widget seems to exist partly to address this).

I guess a custom widget is probably a reasonable solution with gtk3. Probably isn't too hard to fix the behavior here...

**Comment by ids1024** [comment]
For some reason the `HdyCarousel` seem to be using width for height geometry, so this doesn't allocate properly...

**Comment by ids1024** [comment]
Updated, but not quite working. For whatever reason, nothing seems to quite work consistently.

**Pull request closed without merging**
