### PR TITLE
Always show sources

### PR DESCRIPTION
**Pull request by jackpot51**
Addresses comments in #157

### CODE REVIEW

**Review by mmstick — APPROVED** [review]

**Comment by leviport** [comment]
This seems to add lag while it populates a list of applications, such as when you click a category like "Graphics". Opening that category again does not lag a second time unless Pop Shop is closed and reopened.

**Review by leviport — CHANGES_REQUESTED** [review]
So the lag, I think, is okay since it's fairly insignificant. However, before the first item loads, it shows a "No Results" message, which I think we need to do something about. If there can be a 1 or 2 second timeout before showing "No results", it should give a list item the chance to populate.

**Comment by bflanagin** [comment]
Is this PR still relevant?

**Comment by leviport** [comment]
>Is this PR still relevant?

Yes, it's still a feature that would be good to have in Pop Shop.

**Review by bflanagin — CHANGES_REQUESTED** [review]
Though there may be little that can be done about it. The small lag that exists when populating the list also occurs when scrolling through the list  causing visual pauses. This occurs in the standard install of Pop_Shop as well as in this PR. However, with this PR the pauses are significantly more noticeable.

**Pull request closed without merging**
