### PR TITLE
Upstream rebase

### PR DESCRIPTION
**Pull request by isantop**
Updates Pop_Shop to be based on the current elementary AppCenter master. Also restores our minimum-width patches and adds a new "Recently Updated" section to the homepage which lists recently updated applications from Flathub. This improves app discoverability and makes the homepage more dynamic (rather than a static page of Pop_Picks).

The new upstream version appears to be much more reliable when installing and updating applications and packages. It also appears to be more responsive.

QA Testing: 
  * Verify that there are no regressions from current versions
  * Verify that the window can be shrunk to narrow, tileable widths
  * Verify that the Pop_Shop Icon and app name appear as expected

Known Issues:
  * App freezes during initial loading; This also appears in the currently released version.

### CODE REVIEW

**Comment by 13r0ck** [comment]
It might be helpful to pull [this](https://github.com/elementary/appcenter/pull/1752) in too. Rather than making a separate PR after this

**Review by jackpot51 — COMMENTED** [review]
Giving a real code review on something with this many changes is nearly impossible. So, instead, I did the following:

1. I skimmed all changes from the upstream version last merged. They appear to be similar to the changes we had from the previous rebase.
2. I made sure a few changes we made fixing upstream issues, which are not yet upstreamed, were still present.
- In this case, I found what might be an issue in UbuntuDriversBackend.vala. `#if POP_OS` is instead `#if POP_OS_NULL`. Was this intentional?
3. I installed and ran through testing of things that are usually troublesome.
- I needed libgranite 6. This may mean debian/control should be updated? We will need libgranite-6 from https://github.com/pop-os/granite released at some point
- I took a while to load on first launch. The banner was hidden during this time, only categories were shown. This appears to happen on every launch
- I had a crash after installing Slack, then going back to the home page
```
(io.elementary.appcenter:918865): GLib-GObject-WARNING **: 16:55:24.735: invalid cast from 'AppCenterCorePackage' to 'AppCenterCoreFlatpakPackage'
```

**Comment by isantop** [comment]
@jackpot51 Thanks for the feedback. I've made the following changes:

* The banner "carousel" now shows immediately when the window is loaded, rather than waiting for the loading process to complete.
* A duplicate `api_url` option in the `meson_options.txt` file was removed, which appears to remove/reduce the UI lockup during initial loading.
* `libgranite6` and `libhandy-1-0` were added to the control file for packaging.
* The Ubuntu Drivers Backend was revisited. It looks to me like our fixes here were merged upstream some time ago and then subsequently modified. The current version as of d9d6330 seems to work correctly; please check and let me know if that's not the case and I need to look at closer integration of our current modifications. The `null` driver is no longer displayed, and this file tracks the upstream version much more closely, which should greatly reduce maintenance burden going forward.
*

**Comment by jackpot51** [comment]
Thanks @isantop, I will take a look again when the slack install bug is fixed

**Comment by isantop** [comment]
Looks like the problem isn't necessarily limited to Slack, but any package where both a deb and flatpak version are available, and the deb version is installed. After git-bisecting a bit, I traced the problem commit to fdde2b5dc486daff56ec2457428d42ad7dae5df9

I'll need to do some more work to figure out what here is causing the problem.

**Review by 13r0ck — CHANGES_REQUESTED** [review]
<details>
<summary>Cannot scale down to minimum in application view, and causes global scaling to have higher minimum </summary>
<br>

https://user-images.githubusercontent.com/58987761/145302327-b2894d57-2722-48ee-a4f7-19d7abcb8466.mp4

</details>

<details>
<summary>All application names become `...` after a few seconds </summary>
<br>

https://user-images.githubusercontent.com/58987761/145302476-4163724a-75d9-4265-9b35-388bc1e53b3b.mp4

</details>

<details>
<summary>Images are cut off because they are not scaled to fit within the view.</summary>
<br>

https://user-images.githubusercontent.com/58987761/145302526-1bbdcc68-0426-420b-9e8d-4ed57a6bb290.mp4

</details>

<details>
<summary>Main view doesn't have a maximum width like the application views do.</summary>
<br>

https://user-images.githubusercontent.com/58987761/145302759-62d7869d-3069-4cfd-8e47-25958bf00fff.mp4

</details>

**Comment by isantop** [comment]
> All application names become `...` after a few seconds
Do you have a screenshot available showing this issue? I can't seem to replicate this behavior.

> Main view doesn't have a maximum width like the application views do.
No, this is intentional design because it uses a flowbox to flow content in columns to fit the available width. The applications views need a maximum width because A) Having the text in narrower columns makes it easier to read and improves UX and B) Allowing the screenshots to expand to fill the space in a maximized window would make the screenshots too large to view the entire thing in the window, thus we constrain the maximum width.

**Comment by 13r0ck** [comment]
@isantop 
> Do you have a screenshot available showing this issue? I can't seem to replicate this behavior.
Ya, all of the points up there are drop downs with videos

**Comment by isantop** [comment]
@13r0ck I see.

Based on those screenshots, that's not the correct build anyway, as there's some things that aren't matching (also there's some more work on this that I've found anyway which needs to be completed before this is merged).

What are you getting as the ouput of `which io.elementary.appcenter && apt policy pop-shop`?

**Comment by 13r0ck** [comment]
Just for clarity if anyone else reads this.  I was on 3.4.2pop0~1637689735~21.10~69242e0 because of libgranite6 conflicts. Ian said that other issues need to be fixed before this can be properly QA'ed. I'm on standby

**Comment by isantop** [comment]
I think this is now ready for re-review. The missing things from before are now added back and everything seems to be working correctly. 

One note: There it still a maximum width for application views because we can't reflow text into multiple columns with current GTK Widgets, and keeping the text/screenshots narrow aids with UX. The homepage views are allowed to scale up to larger widths because they use flowboxes to make more efficient use of space without harming the usability of the view.

**Comment by 13r0ck** [comment]
<details>
<summary>The open notification doesn't work (skip to 1:00)</summary>
<br>

https://user-images.githubusercontent.com/58987761/146429986-fdf86a4c-a86e-468e-aa3b-c453f690e21e.mp4

</details>

<details>
<summary>`Other Apps` shown when none are available</summary>
<br>

other apps still shown when none available


</details>

<details>
<summary>Screenshots are too small to be useful</summary>
<br>

super small screenshots

more tiny screenshots

</details>

<details>
<summary>Inconsistent spacing above and below section titles</summary>
<br>

strange_spacing

</details>

<details>
<summary>Screenshot arrows are outside app view's width</summary>
<br>

arrows outside of maximum width

</details>

<details>
<summary>Current app is listed in `Other Apps`</summary>
<br>

current app listed as other apps

</details>

### Out of scope of this PR, but still issues

<details>
<summary>Deb has significantly less information than the flatpack. Maybe if an app has both we should show the flatpak's information.</summary>
<br>

deb has less

flatpak has more details

</details>

<details>
<summary>Repoman doesn't scale like Pop!_Shop (I know this will have to be addressed in a different repo anyway.)</summary>
<br>

repoman doesn't scale


</details>

**Review by 13r0ck — CHANGES_REQUESTED** [review]
<details>
<summary>The open notification doesn't work (skip to 1:00)</summary>
<br>

https://user-images.githubusercontent.com/58987761/146429986-fdf86a4c-a86e-468e-aa3b-c453f690e21e.mp4

</details>

<details>
<summary>

~~`Other Apps` shown when none are available~~[fixed](https://github.com/pop-os/shop/pull/311/commits/9a7ebca1834d4c22b8c557673bdbb6d2bf709fdf)</summary>
<br>

other apps still shown when none available


</details>

<details>
<summary>Screenshots are too small to be useful</summary>
<br>

super small screenshots

more tiny screenshots

</details>

<details>
<summary>Inconsistent spacing above and below section titles</summary>
<br>

strange_spacing

</details>

<details>
<summary>
 
~~Screenshot arrows are outside app view's width~~ [fixed](https://github.com/pop-os/shop/pull/311/commits/11549666aa749a584601182fd7c990a6d86f3ece)

</summary>
<br>

arrows outside of maximum width

</details>

<details>
<summary>

~~Current app is listed in `Other Apps`~~[fixed](https://github.com/pop-os/shop/pull/311/commits/9a7ebca1834d4c22b8c557673bdbb6d2bf709fdf)</summary>
<br>

current app listed as other apps

</details>

### Out of scope of this PR, but still issues

<details>
<summary>Deb has significantly less information than the flatpack. Maybe if an app has both we should show the flatpak's information.</summary>
<br>

deb has less

flatpak has more details

</details>

<details>
<summary>Repoman doesn't scale like Pop!_Shop (I know this will have to be addressed in a different repo anyway.)</summary>
<br>

repoman doesn't scale


</details>

**Comment by isantop** [comment]
@13r0ck I'm trouble replicating some of these issues:

<details>
<summary>(The open notification doesn't work) It seems to be working for me, both with Mattermost and another App.</summary>
<br>

https://user-images.githubusercontent.com/5883565/146435901-21688df0-d204-415d-9fea-d8b4efd2b1d9.mp4

</details>

<details>
<summary>(Screenshots are too small to be useful) Again, screenshots seem to be full size for me:</summary>
<br>

Screenshot from 2021-12-16 12-25-55

</details>

<details>
<summary>(Current app is listed in `Other Apps`) This is caused by poor app data where the app IDs are different between the Flatpak and Apt versions.</summary>
<br>

This causes them to be listed twice everywhere in AppCenter/Pop_Shop; if you search for Steam, there are two listings for it in the search results as well. Because the `Other Apps` feature uses the developer name to match these, and they (obviously) have the same author (because they are the same app), they will be listed.

Possible solutions to this include modifying our appdata to set the ID for apt Steam to be the same as the Flatpak version, however I don't think it's appropriate for Pop_Shop to do this filtering itself. There are probably legitimate cases where a developer might need this to be correct, so filtering by AppID is still the best way to do this.

</details>

**Comment by isantop** [comment]
Actually, it seems that the issue showing the Other Apps bar when none are available is related to showing multiple apps with the same name. In this case, we're always getting duplicates for some reason, so filtering by name takes care of both of those.

**Comment by 13r0ck** [comment]
> (The open notification doesn't work) It seems to be working for me, both with Mattermost and another App.

<details>
<summary>I have that one reproducible on both a galp5 and lemp9, does the terminal output help?</summary>
<br>

Screenshot from 2021-12-16 13-23-21

</details>

> (Screenshots are too small to be useful) Again, screenshots seem to be full size for me:

Huh strange. Screenshots are tiny on Galp5, but normal on my Lemp9, let me see if I can nail that down a bit more for you.

**Comment by 13r0ck** [comment]
> Actually, it seems that the issue showing the Other Apps bar when none are available is related to showing multiple apps with the same name. In this case, we're always getting duplicates for some reason, so filtering by name takes care of both of those.
<details>
<summary>I am now seeing no results in Steam, and still two copies of steam when in the steam link app</summary>
<br>

Both on `9a7ebca `

Screenshot from 2021-12-16 13-40-17

Screenshot from 2021-12-16 13-40-45

</details>

> (Screenshots are too small to be useful) Again, screenshots seem to be full size for me:
I can get the issue to reproduce on both a galp5 and a lemp9 by opening and closing the same app view several times in a row. It only happens some of the time

**Comment by isantop** [comment]
@13r0ck 

> I am now seeing no results in Steam, and still two copies of steam when in the steam link app

I think removing the duplicates in cases like the Steam Link app is not a good idea, because we don't necessarily know if the user will end up at the Flatpak or APT version of the package, and there is no way to switch. Currently, if they end up on one they don't want, they can go back and pick the other one. I'd rather limit the filtering to removing duplicates of the App that's currently being viewed, and accept that the corner cases like Steam will happen due to bad appdata and encourage devs to make better appdata in the future. 

> I have that one reproducible on both a galp5 and lemp9, does the terminal output help?

The terminal output does not help in that case, lol. 

This sounds like the appdata was updated post-install somehow and doesn't match what was present earlier. Does it continue happening if you reboot the machine and try again?

> I can get the issue to reproduce on both a galp5 and a lemp9 by opening and closing the same app view several times in a row. It only happens some of the time

Do they stay small if you cycle through the screenshots? I'm thinking the screenshots widgets are missing a `size_allocate` signal or something, and if the screenshot cycles it should re-allocate the sizing and scale them up.

**Comment by 13r0ck** [comment]
> I think removing the duplicates in cases like the Steam Link app is not a good idea, because we don't necessarily know if the user will end up at the Flatpak or APT version of the package, and there is no way to switch. Currently, if they end up on one they don't want, they can go back and pick the other one. I'd rather limit the filtering to removing duplicates of the App that's currently being viewed, and accept that the corner cases like Steam will happen due to bad appdata and encourage devs to make better appdata in the future.

The problem is it doesn't show any indication of which is which. So to the user they are two of the same buttons with different descriptions. It's really confusing. QA only tests for the Pop!_OS .deb, and Pop!_Picks also links to the .deb, so in the case of both maybe we should link to the Pop!_OS .deb?

&

After the last commit the steam app view shows no other apps by steam, when the steam link app should be listed.

> Do they stay small if you cycle through the screenshots? I'm thinking the screenshots widgets are missing a size_allocate signal or something, and if the screenshot cycles it should re-allocate the sizing and scale them up.

Yes they stay small

> Does it continue happening if you reboot the machine and try again?

Rebooting did fix the lemp9 but not the galp5.

> There are now updates to the screenshot arrows as well, please double-check that these match the width of the view.

Yep arrows are now in the right spot. I crossed that off the [list](https://github.com/pop-os/shop/pull/311#pullrequestreview-834497131)

**Comment by isantop** [comment]
> maybe we should link to the Pop!_OS .deb?

This would prevent users from installing the flatpak version, no? I'm also not really comfortable hard-linking any specific apps directly within Pop_Shop. That's a huge maintenance nightmare, and it's really hacky. The correct solution from this point forward is fixing the AppData so that they show up on the same page.

**Comment by 13r0ck** [comment]
> This would prevent users from installing the flatpak version, no? I'm also not really comfortable hard-linking any specific apps directly within Pop_Shop. That's a huge maintenance nightmare, and it's really hacky. The correct solution from this point forward is fixing the AppData so that they show up on the same page.

100% agree, hard-linking is a bad idea. I was thinking:
```
if (app has Pop!_OS .deb && app has flatpack) {
    only show button for Pop!_OS .deb
} else {
    continue as ususal
}
```
I am fine with any other solution you may have, I just don't think we can leave it how it is, where two nearly identical buttons link to two different locations

**Comment by isantop** [comment]
The current behavior (from upstream) is to only show "Other Apps" when there's more than one other app. I'm not sure what the reasoning behind this is, but as of now that should be considered intentional.

**Comment by isantop** [comment]
>  After the last commit the steam app view shows no other apps by steam, when the steam link app should be listed.

Currently the coded behavior (via upstream) is to only show "Other Apps" if there's more than one other app available. I'm not sure if this is the way that's supposed to go, or if someone did `<=` when they should have done `<`. 

> 100% agree, hard-linking is a bad idea. I was thinking:

This would prevent users from installing a flatpak version, for which there are very many possible reasons to do so. The correct solution in the Steam issue is to update our AppData package and fix the AppID for Steam; Pop_Shop is working as intended.

**Comment by 13r0ck** [comment]
> Currently the coded behavior (via upstream) is to only show "Other Apps" if there's more than one other app available. I'm not sure if this is the way that's supposed to go, or if someone did <= when they should have done <.

That sound like an issue that we should fix here, then upstream after.

> This would prevent users from installing a flatpak version, for which there are very many possible reasons to do so. The correct solution in the Steam issue is to update our AppData package and fix the AppID for Steam; Pop_Shop is working as intended.

When searching for steam and 0ad only one result shows. There is some way that Pop!_Shop is filtering results there, we could do the same here.
I am not to familiar with AppData not AppID, but if you can make a PR there that fixes the issue here, I would be happy to approve it and then we can move on from this.

**Comment by 13r0ck** [comment]
Showing other apps with just one works great thank you!

It might make sense to rephrase it as "Also by <Software developer>", because then it wouldn't have the plural of "Other Apps" when there is only one. But that is up to your preference. I am not going to consider that blocking.

**Comment by isantop** [comment]
> Showing other apps with just one works great thank you!
> 
> It might make sense to rephrase it as "Also by ", because then it wouldn't have the plural of "Other Apps" when there is only one. But that is up to your preference. I am not going to consider that blocking.

This copy is remaining as-is; changes create a maintenance difference with the upstream codebase. I also don't think it's as grammatically awkward as claimed. ("Are there any other apps by this author?" "Yes, this one")

I've pushed a new commit that helps to filter out duplicates. It's removing additional apps by the same author with the same name. Hopefully that shouldn't be a problem as most authors won't be publishing multiple different apps with the same names.

**Comment by jacobgkau** [comment]
> This copy is remaining as-is; changes create a maintenance difference with the upstream codebase.

Aren't we making other changes in this PR?

> I also don't think it's as grammatically awkward as claimed. ("Are there any other apps by this author?" "Yes, this one")

I haven't seen this for myself, but based on Brock's description, it does sound incorrect to say "apps" and then list one app, even if it's not "awkward." If we're making the change that creates this problem (show the section even with only one app), it seems like changing the copy would be part of that.

**Comment by isantop** [comment]
> Aren't we making other changes in this PR?

Yes, but every change we make has the potential to become a merge conflict in the future. It adds to future maintenance burden, so it's better to be extremely deliberate with changes and ensure that we aren't making the codebase less maintainable. 

Looking at other App Stores, it might then make sense to ensure that the Other Apps section is only showed when there are two or more other apps available. For example, the Play Store on Android shows their "Other apps" section when there are multiple other apps by that developer available. Looking for apps published by The Tor Project shows they have four apps published, but the Play Store doesn't show other apps in each app's listing; meanwhile, apps by Microsoft do (as Microsoft has a very large number of published apps).

**Comment by 13r0ck** [comment]
If you do not want to change the copy I think that is fine, but I would argue that always showing apps by the same developer, even if it is just one should be kept. As it greatly improves app discovery. Just from testing the other apps section, I found new apps I didn't know existed.

**Comment by isantop** [comment]
@13r0ck The copy has been updated

**Comment by 13r0ck** [comment]
Awesome!
The last things from [above](https://github.com/pop-os/shop/pull/311#pullrequestreview-834497131) are :
- [ ] Screenshots are too small (sometimes)
- [ ] Open button doesn't work

I'm not sure where it has to be resolved, but Pop!_Shop still doesn't update without having to install libgranite6 first

**Comment by 13r0ck** [comment]
elementary/appcenter#1752 just got merged. I think we should put that in here too, shouldn't conflict with anything

**Comment by isantop** [comment]
@13r0ck The copy has been updated

> [elementary#1752](https://github.com/elementary/appcenter/pull/1752) just got merged. I think we should put that in here too, []my commit]([elementary@5495088](https://github.com/elementary/appcenter/commit/549508815d1882ec41ad69ccec5d2c0aef46c4be)) shouldn't conflict with anything

@13r0ck I think for this PR it would be better to get this merged as-is, then pull in the upstream changes since this was authored, rather than trying to cherry-pick across forks

**Comment by isantop** [comment]
Should now be good for review

**Comment by 13r0ck** [comment]
@XV-02

**Comment by jacobgkau** [comment]
I've had a few instances where an app displays its screenshots at the wrong size, but only some of the time. Here's an example:

https://user-images.githubusercontent.com/7199422/155215139-8a3e89c6-c32d-4c24-8ee8-bd0a1d5586bd.mp4

**Comment by isantop** [comment]
Should now be good for review

> I've had a few instances where an app displays its screenshots at the wrong size, but only some of the time. Here's an example:
> simplescreenrecorder-2022-02-22_13.33.39.mp4

@jacobgkau I think that's a limitation of the way the system currently works. I can get it to happen, but there's not a specific set of things that seems to trigger it every time I try it.

**Comment by jacobgkau** [comment]
> @jacobgkau I think that's a limitation of the way the system currently works. I can get it to happen, but there's not a specific set of things that seems to trigger it every time I try it.

I'm not sure what you're trying to say, but it doesn't happen with the currently-released version and it does happen on this branch, so it's a regression.

**Review by 13r0ck — CHANGES_REQUESTED** [review]
@jacobgkau @isantop 
I created a PR into this PR that fixes the screenshot scaling issue.

**Comment by jacobgkau** [comment]
When using this branch, I'm not seeing `io.elementary.appcenter` running on a fresh login, and it's not notifying me of updates on boot/login or e.g. after adding a staging repo.

https://github.com/pop-os/upgrade/pull/225 will require pop-shop to stop notifying about updates when it's ready, but it's not ready yet, and this also doesn't seem entirely intentional because I do get update notifications after opening the Pop!_Shop and _sometimes_ after closing it again (`io.elementary.appcenter` doesn't always continue running after closing, but I've seen it keep running at least once.)

**Comment by isantop** [comment]
@jacobgkau I can't seem to reproduce that issue. It does occasionally take a couple of minutes before the Pop_Shop starts, but it does start and notify about updates every time I reboot.

**Comment by jacobgkau** [comment]
> It does occasionally take a couple of minutes before the Pop_Shop starts,

I see, there's a delay. I am now seeing it start consistently about a minute after boot/login, and give a notification if there are updates.

I don't see notifications immediately after adding staging repos like I used to (which would be after a source has changed)-- not sure if anything changed with what triggers a notification or a background update check, but I don't think a background update check notification is necessarily required in that situation since the user would have just manually made an update to their sources, which they would be aware of.

@n3m0-22's been taking a look at this, and he found similar issues to what I reported previously (process exiting with the Pop!_Shop app, along with a weird notification glitch where it would go straight to the notifications drop-down without popping up first which I have not seen in my own testing). We're trying to figure out why the process might still be exiting for him when it's not for me. In any case, https://github.com/pop-os/upgrade/pull/225 will replace the Pop!_Shop's notifications (and require them to be disabled), so even if there are issues, they won't be relevant for too much longer.

Can we get the conflict resolved now that https://github.com/pop-os/shop/pull/340 was merged adding two apps to the picks?

**Comment by isantop** [comment]
@jacobgkau I just resolved the conflict there (adding Deja Dup and Chromium). Should be set.

**Review by n3m0-22 — APPROVED** [review]

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
