### PR TITLE
Hide open NVIDIA drivers

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by ids1024 — DISMISSED** [review]

**Comment by XV-02** [comment]
I touch Pop!_Shop only once in a blue moon. Does it cache avaliable packages anywhere on first launch? I ask as I'm still seeing the open driver after switching to this version of the package.

**Comment by jacobgkau** [comment]
> I touch Pop!_Shop only once in a blue moon. Does it cache avaliable packages anywhere on first launch? I ask as I'm still seeing the open driver after switching to this version of the package.

I don't think it would cache available drivers like that. We haven't had that kind of issue while testing older NVIDIA driver listing issues, and `~/.cache/elementary.io.appcenter/` doesn't seem to have it.

**Review by jacobgkau — CHANGES_REQUESTED** [review]
Confirmed [dba1a2f](https://github.com/pop-os/shop/pull/413/commits/dba1a2f20b7d736509393790579292988c30eeab) is not working to hide the open driver.

Screenshot from 2023-08-11 17-08-57

**Comment by XV-02** [comment]
I can confirm that this is working as intended (once pop-shop is restarted, but that makes sense.)

@jacobgkau if you concur, do you want to approve this?

**Review by jacobgkau — APPROVED** [review]
Before:
Screenshot from 2023-08-14 14-13-00
After:
Screenshot from 2023-08-14 14-13-52

**Review by ids1024 — APPROVED** [review]

**Pull request merged**
