### PR TITLE
Search improvements

### LINKED ISSUE #375: Searching directly without clicking on the search bar
**Distribution (run `cat /etc/os-release`):**
 
    NAME="Pop!_OS"
    VERSION="22.04 LTS"
    ID=pop
    ID_LIKE="ubuntu debian"
    PRETTY_NAME="Pop!_OS 22.04 LTS"
    VERSION_ID="22.04"
    HOME_URL="https://pop.system76.com"
    SUPPORT_URL="https://support.system76.com"
    BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
    PRIVACY_POLICY_URL="https://system76.com/privacy"
    VERSION_CODENAME=jammy
    UBUNTU_CODENAME=jammy
    LOGO=distributor-logo-pop-os

 **Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

    io.elementary.appcenter

**Issue/Bug Description:**

Earlier I could open pop shop and directly type in whatever I want to search  
But since a few days, I need to click the search bar in Pop Shop before searching anythng

**Steps to reproduce (if you know):**

1. Open Pop Shop
2. Type in search string
3. Nothing happens (unless I go and click the search bar)

**Expected behavior:**

1. Open Pop Shop
2. Type in search string
3. Package search success

**Other Notes:**

If this was an intentional 'update',  I personally feel this more like a downgrade and I'm sure I'm not alone

### PR DESCRIPTION
**Pull request by isantop**
Improves the search bar in Pop_Shop in the following ways:

* Allows the search bar to grab focus whenever the user starts typing and the search bar is not disabled. This allows users to type a search query in at any time without needing to explicitly click on the search bar first. Fixes #375 
* Improves the CSS styling of the search bar to make it more visually distinct when disabled. This helps make it more clear when the search is disabled and cannot be focused.

The search focus improvements should not affect usability outside of aiding the user to search without needing to explicitly focus the search bar first. It should skip most non-typing characters and pass the keycode unmodified to GTK. It also ignores all processing when the search bar already has focus. The Application can be used normally when the search bar is focused, so it shouldn't affect anything there either.

### CODE REVIEW

**Comment by n3m0-22** [comment]
Should search be enabled while on an apps page?

**Review by n3m0-22 — CHANGES_REQUESTED** [review]
When clicking show details for some apps it is searching instead of bringing up the apps page. For example show details for the Inkscape Flatpak searches for `org.inkscape.Inkscape.desktop` which finds LyX, and GIMP Flatpak searches `org.gimp.GIMP.desktop` and finds BleachBit. This seems to be affecting Flatpaks, but not all. Signal and Meld bring up the app page. Also if you show details on a .deb for example `dconf-editor` right after one of the Flatpak issues listed above the search field still shows the text that was searched for.

GIMP Show Details:

Screenshot from 2022-07-25 17-39-36

dconf Editor Show Details after GIMP:

Screenshot from 2022-07-25 17-39-48

**Comment by n3m0-22** [comment]
If the search box being disabled on an app page as well as the Installed page is correct behavior this is ready to go. All other regression testing has passed. I am now able to use the search box without selecting it from home and category pages. It is also much clearer now when the search box is disabled.

**Review by mmstick — APPROVED** [review]

**Review by n3m0-22 — APPROVED** [review]
Confirmed this is working as expected.

**Comment by realKarthikNair** [comment]
Thank you guys

**Pull request merged**
