### PR TITLE
Keyboard Navigation Support

### PR DESCRIPTION
**Pull request by mmstick**
- App lists are navigatable with the arrow keys
  - If an arrow key is used and no package is selected, select the first app in the list
  - The space key will install the selected package
  - The enter key will open the app info view for the selected package
- App info views also support keyboard navigation now
  - The space key will install / uninstall the app
  - The arrow keys will scroll the view
  - PgUp & PgDn will also scroll the view
- Ctrl + F switches focus to the search
- Backspace returns to previous view

### CODE REVIEW

**Comment by cassidyjames** [comment]
@mmstick a lot of this behavior should be handled out of the box in GTK, so it feels weird to be adding a bunch of key events here. Are we seeing a bug where keyboard events aren't working right? i.e. in AppCenter upstream, I can navigate the homepage items with the arrow keys, page up/down the list in updates or categories, use Enter to open items that have the keyboard focus, etc.

I'm also nor a fan of adding secret keyboard shortcuts like `o` to open things, since that's not a convention anywhere else and might lead to unexpected behavior.

**Comment by mmstick** [comment]
@cassidyjames I think it may be the search entry which grabs focus and takes all keyboard input away from the window.

**Comment by cassidyjames** [comment]
@mmstick since only one thing can have focus at a time, that sounds somewhat correct. But can't you just tab away from it and use the keyboard like normal?

**Comment by cassidyjames** [comment]
>Before, keyboard navigation did not work at all. Now it works throughout the application.

I'm still not seeing this "did not work at all" behavior in master or in upstream. I can tab around and use arrow keys mostly as expected, so I'm not really sure what some of this is solving.

> - App lists are navigatable with the arrow keys
>   - If an arrow key is used and no package is selected, select the first app in the list

That sounds like a sane improvement. Right now you can tab to it, but can't just hit an arrow key.

>   - The space key will install the selected package
>   - The enter key will open the app info view for the selected package

I'm still not a fan of these operating differently. In all other GTK contexts, these both just activate/press whatever is focused. You can already tab specifically to the buttons to perform actions. In master it already works that way as well, so I think some of this code is unnecessary duplication of built-in GTK behavior.

> - App info views also support keyboard navigation now
>   - The space key will install / uninstall the app

Same as above, this is weird and nonstandard. Tabbing to the buttons to focus them already works, and hitting Enter or Space on the buttons already installs/uninstalls/opens them.

>   - The arrow keys will scroll the view
>   - PgUp & PgDn will also scroll the view

These sound like sane improvements.

> - Ctrl + F switches focus to the search

Also sounds sane!

**Pull request closed without merging**
