### PR TITLE
Rebase eoan branch on latest upstream commits

### PR DESCRIPTION
**Pull request by mmstick**
> This PR cannot be merged, and must be force-pushed.

### CODE REVIEW

**Comment by isantop** [comment]
@mmstick When I install this version, I can't seem to see any flatpak apps (after having added Flatpak manually)

**Comment by mmstick** [comment]
@isantop Did you also add Flathub?

**Comment by mmstick** [comment]
@isantop As well as killing all the appcenter services running in the background with `kill $(pidof io.elementary.appcenter)`?

**Comment by isantop** [comment]
@mmstick Yes, I meant that I added Flathub manually. And it continues to display no Flatpak apps even after a reboot.

**Comment by mmstick** [comment]
@isantop Unsure what's going on there.

I have

```
pop-shop:
  Installed: 3.1.1pop0~1574113524~19.10~029bcb5
  Candidate: 3.1.1pop0~1574113524~19.10~029bcb5
  Version table:
 *** 3.1.1pop0~1574113524~19.10~029bcb5 1002
       1002 http://apt.pop-os.org/staging/pop-rebase eoan/main amd64 Packages
```

And Flathub works

Screenshot from 2019-11-19 15-03-49

**Comment by isantop** [comment]
```
 %  apt policy pop-shop
pop-shop:
  Installed: 3.1.1pop0~1574113524~19.10~029bcb5
  Candidate: 3.1.1pop0~1574113524~19.10~029bcb5
  Version table:
 *** 3.1.1pop0~1574113524~19.10~029bcb5 1002
       1002 http://apt.pop-os.org/staging/pop-rebase eoan/main amd64 Packages
        100 /var/lib/dpkg/status
     3.0.1~1572642128~19.10~67df78f 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/proposed/ubuntu eoan/main amd64 Packages
 16:12  ~ 
 %  flatpak remote-list
Name    Options
flathub system
```

Screenshot from 2019-11-19 16-13-30

**Comment by cassidyjames** [comment]
@isantop https://github.com/elementary/appcenter/issues/1115

**Comment by isantop** [comment]
@mmstick Given @cassidyjames 's comment above, I think we should configure our fork to handle system-wide flatpak installs in addition to user-installs

**Comment by mmstick** [comment]
Definitely

**Comment by cassidyjames** [comment]
>I think we should configure our fork to handle system-wide flatpak installs in addition to user-installs

Note that this is a wanted feature upstream (https://github.com/elementary/appcenter/issues/1074), so working there would benefit you all as well (and then we'd be maintaining it).

**Comment by isantop** [comment]
@mmstick I'm going to push an application.css change to get rid of the light background for text in app descriptions.

**Comment by brs17** [comment]
> @mmstick I'm going to push an application.css change to get rid of the light background for text in app descriptions.

@isantop is this fix one that exists in the current version of Pop!_Shop?

**Comment by isantop** [comment]
> > @mmstick I'm going to push an application.css change to get rid of the light background for text in app descriptions.
> 
> @isantop is this fix one that exists in the current version of Pop!_Shop?

This issue has popped up and gone away several times, mostly because we used to be patching this out in the theme. This moves the fix directly to the application, and uses exported theme colors to ensure that they should match with a wide variety of themes (Tested in Adwaita, Pop, Yaru, and Arc).

**Comment by brs17** [comment]
> > > @mmstick I'm going to push an application.css change to get rid of the light background for text in app descriptions.
> > 
> > 
> > @isantop is this fix one that exists in the current version of Pop!_Shop?
> 
> This issue has popped up and gone away several times, mostly because we used to be patching this out in the theme. This moves the fix directly to the application, and uses exported theme colors to ensure that they should match with a wide variety of themes (Tested in Adwaita, Pop, Yaru, and Arc).

Please revert this commit from this pr as this pr deals with rebasing on upstream. 

Feel free to make this patch it's own pr either based on the current version of Pop!_Shop, or a PR based on this PR.

Thank you.

**Comment by isantop** [comment]
@brs17 Following that logic, 029bcb5 should also be reverted, no?

**Comment by brs17** [comment]
> @brs17 Following that logic, [029bcb5](https://github.com/pop-os/shop/commit/029bcb565bada9ebb6d2d5db402324d149757b55) should also be reverted, no?

@isantop a PR should successfully build, so that commit was necessary to make this a valid pr and therefore should not be removed.

**Comment by isantop** [comment]
@brs17 Reverting that commit does introduce bugs to master that weren't previously present. I have checked in a clean install, and a fully-updated Pop_Shop does not exhibit the white-background on App descriptions

**Pull request closed without merging**
