### PR TITLE
Rebase focal

### PR DESCRIPTION
**Pull request by mmstick**
Rebase on elementary

One of the new features we get is system-wide flatpaks

[Our changes](https://github.com/pop-os/shop/pull/217/commits/f7c19c4b827d3545a1e91ce899b82f6b76ddce21)

### CODE REVIEW

**Comment by ids1024** [comment]
Build failure on CI:

```
meson.build:32:0: ERROR: Dependency "polkit-gobject-1" not found, tried pkgconfig
dh_auto_configure: error: cd obj-x86_64-linux-gnu && LC_ALL=C.UTF-8 meson .. --wrap-mode=nodownload --buildtype=plain --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=lib/x86_64-linux-gnu --libexecdir=lib/x86_64-linux-gnu returned exit code 1
make: *** [debian/rules:15: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 
```

Looks like that dependency was added in 87e510471. Should be easy to fix.

**Comment by WatchMkr** [comment]
How do you know if you're installing a flatpak for your user or system-wide?

**Comment by mmstick** [comment]
The source is listed as `system-wide $REPO`, same as on elementary now

**Review by jacobgkau — CHANGES_REQUESTED** [review]
https://github.com/pop-os/shop/issues/218 is happening before and after this update, so I opened an issue for it.

I see a styling regression with this update. If I search for an app, select a search result, then navigate back to the list of search results, the last-selected result was not highlighted before this update:

shop-pr217-screenshot7

After the update, the last-selected search result is highlighted:

shop-pr217-screenshot5

The only reason this is an issue is because the `Install` button on the highlighted item has black text on a dark background.

I'm also seeing metadata regressions for several apps. Peek has a screenshot before the update, but not after the update:

shop-pr217-screenshot6

shop-pr217-screenshot4

Additionally, the issue I described in https://github.com/pop-os/shop/issues/218 affects at least one application after the update that it did not affect before the update. If I navigate to Video -> FMIT, it displays properly before the update, but its title is an ellipsis after the update (this could be related to the fact that the .deb and Flatpak were not grouped before the update, but are grouped with a drop-down after the update.)

**Comment by jacobgkau** [comment]
Regarding system-wide Flatpak support, it looks like Flathub is not present system-wide by default, so I had to add that with `$ flatpak remote-add --system flathub https://dl.flathub.org/repo/flathub.flatpakrepo` and then restart the Pop Shop several times before I saw `flathub (system-wide flatpak)` appear as an option in the drop-down for Flatpak apps.

**Comment by mmstick** [comment]
Yes, we don't add the system flatpak in Pop!_OS by default, since it wasn't supported by appcenter

**Comment by mmstick** [comment]
They may have changed the style classes or widget layout for this new update, so our GTK theme may need an update here

**Comment by cassidyjames** [comment]
@mmstick if I recall, Pop!_OS used to carry a patch that disabled selection in rows in search results. It's possible that patch hasn't been re-applied?

**Review by bflanagin — CHANGES_REQUESTED** [review]
I'm noticing all the issues Jacob mentioned, and I would also like to add that when the item is highlighted the install button is very hard to read in dark mode. 

With this rebase would it be possible to automatically add the systemwide flatpak repo now that the ability has been added to the shop? Or would that be better served by another package?

**Comment by ids1024** [comment]
Superseded by https://github.com/pop-os/shop/pull/258.

**Pull request closed without merging**
