### PR TITLE
Rebase on upstream version 7.3.0

### PR DESCRIPTION
**Pull request by jacobgkau**
This is a true rebase, starting from the upstream [7.3.0 tag](https://github.com/elementary/appcenter/tree/7.3.0) and adding actively-desired changes back. This is upstream's latest release, made on June 27th.

This only needs to be tested on jammy since focal and bionic have their own `master_` branches.

Obsoletes https://github.com/pop-os/shop/pull/401. (UX discussions from that PR as well as https://github.com/pop-os/repoman/pull/113 have been taken into account here.)

Tested & working:
- [X] Installing, opening, and removing a .deb app.
- [X] Installing, opening, and removing a Flatpak app.
- [X] Installing mixed .deb/Flatpak updates.
- [X] The menu items and keyboard shortcuts for opening the Automatic Update settings and Repoman.

### CODE REVIEW

**Comment by mmstick** [comment]
Does this fix the crashes that we were seeing before?

**Comment by mmstick** [comment]
This does appear to have fixed the crashes. Categories are slow to load, but that's probably because the category views aren't paginated.

**Comment by jacobgkau** [comment]
Yeah, it seemed to be more stable than the previous rebase during my limited testing so far.

**Comment by jacobgkau** [comment]
I'm just fighting with Vala trying to get the buttons in the InstallFailDialog to work properly at this point. (Upstream changed how the response is connected when they added a new Flatpak repair button to theirs.)

**Comment by jacobgkau** [comment]
Finally got our custom InstallFailDialog options working.

Now working on making updates work.

**Comment by jacobgkau** [comment]
Fixed that error message, updates are working normally now.

The Pop!_Shop/AppCenter's still not perfect, but I think all of the regressions from the currently-released version have been addressed now. This still needs full regression testing from another QA member. Engineering review might want to take a look at the patch commits (I made the most minimal changes possible in an effort to help stability.)

**Review by mmstick — DISMISSED** [review]

**Review by mmstick — APPROVED** [review]

**Comment by leviport** [comment]
I want to take a little more time looking at this, but so far it's looking very good. Stability seems to be greatly improved, and I haven't found anything that doesn't seem to be working right.

**Review by leviport — APPROVED** [review]

**Pull request merged**
