### PR TITLE
Upstream Code Changes

### PR DESCRIPTION
**Pull request by mmstick**
- Includes only the code-related changes.
- Adds new application categories to the home page.
- Requires a change to the GTK theme to [add these predefined CSS colors](https://github.com/elementary/stylesheet/blob/1097c52a29d305417abe18e00c156ed06005e7bf/elementary/gtk-3.0/palette.css) (https://github.com/pop-os/gtk-theme/pull/237)

### CODE REVIEW

**Comment by brs17** [comment]
This pr looks good to me, will not approve until https://github.com/pop-os/gtk-theme/pull/237 looks good as well.

**Comment by isantop** [comment]
Updating to note that this PR is dependent on either pop-os/gtk-theme#237 or pop-os/gtk-theme#257 now.

**Comment by brs17** [comment]
With all of the fixes in place now, @jackpot51 this look good to you (visually)?

screenshot from 2018-12-19 14-37-13

**Comment by brs17** [comment]
@isantop Thank you for your work in getting this looking good. Cosmic looks good but with bionic on a different theme, the categories are quite white and not ready.

**Comment by isantop** [comment]
@brs17 That would require removing support for

**Comment by isantop** [comment]
Was not supposed to be closed, sorry

**Comment by isantop** [comment]
That's going to require pretty substantial deviations from upstream if we want to do that then, since that's something implemented there.

**Comment by mmstick** [comment]
:tada:

**Pull request merged**
