### PR TITLE
Fix all of the UI freezes in the shop

### PR DESCRIPTION
**Pull request by mmstick**
All issues with the UI freezing, being unable to queue multiple downloads at the same time, and pop ups asking the user if they want to forcefully quit the program should be resolved now.

### CODE REVIEW

**Comment by brs17** [comment]
In testing these changes I first attempted to install 2 programs at once. That was successful.

**Comment by brs17** [comment]
Will continue testing tomorrow

**Comment by brs17** [comment]
When installing two applications at the "same time" and then selecting a codec that is already installed. Pop!_Shop freezes. I notice with or without the patch, selecting a codec seems to take longer to load than other applications already installed.

**Comment by brs17** [comment]
Fixes: https://github.com/pop-os/shop/issues/30

**Comment by mmstick** [comment]
There's probably a packagekit operation happening that's causing it to block until all other packagekit operations have been processed.

**Comment by brs17** [comment]
Seeing that this pr vastly improves functionality in the Pop!_Shop and the issue I found a somewhat minor/probably not common usecase, I am tempted to approve the pr so that we can get this fix in production. 

Thoughts? @mmstick @jackpot51

**Comment by mmstick** [comment]
@brs17 Given that the upstream project has merged it, I think it's fine to merge this now.

**Pull request merged**
