### PR TITLE
fix(upgrade-fail-dialog): Segfault on undefined error property after object construction

### LINKED ISSUE #341: [22.04] Crashing due to unresolvable apt dependencies
**Distribution (run `cat /etc/os-release`):** 22.04 LTS
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** 2100231 (master) and 7116406 (upstream-rebase)

**Issue/Bug Description:** This morning, `gnome-remote-desktop` is being held back for some reason, and apt thinks that `gnome-control-center` is not satisfying a dependency for `pop-desktop`. These issues would probably be separate from the Pop!_Shop.

However, rather than displaying an error dialogue, the Pop!_Shop is segfaulting. This is near the end of the terminal output:

```
(io** (io.elementary.appcenter:8809): WARNING **: 09:25:48.076: Package.vala:567: Operation failed for package Operating System Updates - The following packages have unmet dependencies:
  pop-desktop: Depends: gnome-control-center but it is not installable
               Recommends: io.elementary.sideload but it is not installable


(io.elementary.appcenter:8809): GLib-GObject-CRITICAL **: 09:25:48.078: g_value_get_pointer: assertion 'G_VALUE_HOLDS_POINTER (value)' failed
Segmentation fault (core dumped)
```

**Steps to reproduce (if you know):** Open the Pop!_Shop on a 22.04 system and try to install/upgrade packages.

**Expected behavior:** No crash should occur and an error dialogue should appear if the operation is not successful.

**Other Notes:** Not caused by or fixed by the upstream-rebase branch.

### LINKED ISSUE #353: Segmentation fault when attempting to uninstall VIM (ubuntu-minimal dependency)
**Distribution (run `cat /etc/os-release`):**
 
 22.04
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

VIM (text editor)

**Issue/Bug Description:**

PopShop unexpectedly terminates if you try to uninstall.

**Steps to reproduce (if you know):**

Open PopShop. Go to Installed. Scroll down until you see VIM. Click Uninstall. In the middle of the process, PopShop just closes.

**Expected behavior:**

(Obvious)

**Other Notes:**

### LINKED ISSUE #356: Crashing due to Ubuntu phased updates
**Distribution (run `cat /etc/os-release`):** Pop!_OS 22.04
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** 2694a09 (master)

**Issue/Bug Description:** Ubuntu is currently running phased updates, which causes apt to see some packages as having updates available but being held back:

Screenshot from 2022-05-19 14-55-28

The Pop!_Shop also sees updates available, and when I try to install the updates, the Pop!_Shop just closes itself.

**Steps to reproduce (if you know):** Try to run updates while Ubuntu is releasing phased updates.

**Expected behavior:** The Pop!_Shop should not crash. If phased updates can't be installed, the Pop!_Shop should not report that updates are available. (We may want to separately consider disabling Ubuntu phased updates.)

**Other Notes:** This is the Pop!_Shop's terminal output when this happens:

```
** (io.elementary.appcenter:5318): WARNING **: 14:59:29.592: Package.vala:567: Operation failed for package Operating System Updates - The following packages have unmet dependencies:
  pop-desktop: Depends: pop-session but it is not going to be installed
               Depends: chrome-gnome-shell but it is not going to be installed
               Depends: gdm3 but it is not going to be installed
               Depends: gnome-shell but it is not going to be installed
               Conflicts: pulseaudio
               Recommends: gnome-contacts but it is not going to be installed
               Recommends: io.elementary.sideload but it is not installable
               Recommends: gnome-remote-desktop but it is not going to be installed
               Recommends: gnome-shell-extension-prefs but it is not going to be installed
               Conflicts: pulseaudio


(io.elementary.appcenter:5318): GLib-GObject-CRITICAL **: 14:59:29.594: g_value_get_pointer: assertion 'G_VALUE_HOLDS_POINTER (value)' failed
Segmentation fault (core dumped)
```

Apt does not complain about any dependency issues.

### LINKED ISSUE #358: Pop Shop crashes when installing GNOME Hex Editor
**OS Release:**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
 
 
**Related Application and/or Package Version:** io.elementary.appcenter
I don't know how to view the version of this application. 

**Issue/Bug Description:**
Application crashes when trying to install GNOME Hex editor

**Steps to reproduce (if you know):**
1. Launch Pop Shop
2. Search GNOME Hex Editor
3. Click install, enter admin password
4. Pop Shop Crashes

**Expected behavior:**
1. GNOME Hex Editor is installed after providing admin password in Pop Shop

**Other Notes:**
1. I think I have disabled flatpaks somehow, because I can't seem to find chromium on the shop either. Running flatpak through the command line works
2. Running Pop Shop from the command line gives the following output before crashing:
```
** (io.elementary.appcenter:101624): WARNING **: 07:42:13.932: Package.vala:567: Operation failed for package GNOME Hex Editor - The following packages have unmet dependencies:
  libgail-3-0: Depends: libgtk-3-0 (= 3.24.33-1ubuntu1) but 3.24.33-1ubuntu2 is to be installed


(io.elementary.appcenter:101624): GLib-GObject-CRITICAL **: 07:42:13.933: g_value_get_pointer: assertion 'G_VALUE_HOLDS_POINTER (value)' failed
zsh: segmentation fault (core dumped)  io.elementary.appcenter
```

### LINKED ISSUE #381: pop!_shop exits on it own sometimes without giving any error message
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
 

**Issue/Bug Description:**
when i  open pop stop it load some second and exit its own and doesn't give any error 

**Steps to reproduce (if you know):**
when you open pop shop and go to some category it loads some second and exit on its own and it doesn't even give any error message

**Expected behavior:**
its shouldn't exist on it own

### LINKED ISSUE #386: Pop Shop invalid pointer (crash) whenever flathub.org returns 503
**Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Any flatpak package

**Issue/Bug Description:**

Flathub.org was experiencing some network issues and returning 503 Service Unavailable. This resulted in Pop Shop crashing without a message. The journalctl log files revealed that the 503 was resulting in what looks like an invalid pointer:

```
Sep 06 20:16:01 rosie io.elementary.appcenter[6498]: libostree HTTP error from remote flathub for <https://dl.flathub.org/repo/delta-indexes/Zr/yDdXgzAgc6g5tHLhGm65wn7l0jVICjeFSdoh3uPKc.index>: Server returned status 503: Service Unavailable
Sep 06 20:16:01 rosie io.elementary.a[6498]: FlatpakBackend.vala:1147: Flatpak installation failed: While pulling app/com.github.Murmele.Gittyup/x86_64/stable from remote flathub: Server returned status 503: Service Unavailable
Sep 06 20:16:01 rosie io.elementary.a[6498]: Package.vala:577: Operation failed for package Gittyup - Aborted due to failure (While pulling app/com.github.Murmele.Gittyup/x86_64/stable from remote flathub: Server returned status 503: Service Unavailable)
Sep 06 20:16:01 rosie io.elementary.a[6498]: g_value_get_pointer: assertion 'G_VALUE_HOLDS_POINTER (value)' failed
```

**Steps to reproduce (if you know):**

When flathub.org is returning 503s, try to install any flathub package.

**Expected behavior:**

Pop Shop should show an error indicating flathub is down, or that flathub is returning a 503 error code.

### LINKED ISSUE #387: Shop crashes with error: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
pop-shop:
  Instalado: 3.4.2pop0~1659553725~22.04~cdc74cf
  Candidato: 3.4.2pop0~1659553725~22.04~cdc74cf
  Tabela de versão:
 *** 3.4.2pop0~1659553725~22.04~cdc74cf 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

Pop-shop crashes with error:

(io.elementary.appcenter:85479): GLib-GObject-CRITICAL **: 16:24:42.546: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Steps to reproduce (if you know):**

Open pop-shop, select one of the sections (for example Internet) and wait a few seconds. The window dissapears and the application crashes. 

Odd enough, it does not crash if I start with

G_MESSAGES_DEBUG=all io.elementary.appcenter

**Expected behavior:**

I should be able to browser the sections.

**Other Notes:**

### LINKED ISSUE #393: Segfault on 404 on the PPA (when apt is locked)
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
$ apt policy pop-shop
pop-shop:
  Installed: 3.4.2pop0~1659553725~22.04~cdc74cf
  Candidate: 3.4.2pop0~1659553725~22.04~cdc74cf
  Version table:
 *** 3.4.2pop0~1659553725~22.04~cdc74cf 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status

$ apt policy packagekit
packagekit:
  Installed: 1.2.5-2ubuntu2
  Candidate: 1.2.5-2ubuntu2
  Version table:
 *** 1.2.5-2ubuntu2 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

When using the Pop Shop to update, if it fails with a 404 when retrieving stuff, it seems:
```
sep 27 08:50:13 odys PackageKit[1822]: uid 1000 is trying to obtain org.freedesktop.packagekit.system-update auth (only_trusted:1)
sep 27 08:50:14 odys PackageKit[1822]: new update-packages transaction /3060_ababccac scheduled from uid 1000
sep 27 08:50:14 odys PackageKit[1822]: uid 1000 obtained auth for org.freedesktop.packagekit.system-update
sep 27 08:50:14 odys io.elementary.a[19801]: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed
sep 27 08:50:14 odys io.elementary.a[19801]: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed
sep 27 08:50:16 odys packagekitd[1822]: http://apt.pop-os.org/release jammy/main amd64 pop-launcher amd64 1.2.1~1662488179~22.04~6e2fa02 is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
sep 27 08:50:16 odys packagekitd[1822]: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-ar amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
sep 27 08:50:16 odys packagekitd[1822]: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-zh-hant amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
sep 27 08:50:16 odys packagekitd[1822]: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-zh-hans amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
sep 27 08:50:16 odys packagekitd[1822]: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-ru amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
sep 27 08:50:16 odys packagekitd[1822]: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-pt amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
sep 27 08:50:16 odys packagekitd[1822]: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-ja amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
sep 27 08:50:16 odys packagekitd[1822]: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-it amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
sep 27 08:50:16 odys packagekitd[1822]: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-fr amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
sep 27 08:50:16 odys packagekitd[1822]: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-es amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
sep 27 08:50:16 odys packagekitd[1822]: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-en amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
sep 27 08:50:16 odys packagekitd[1822]: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-de amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
sep 27 08:50:16 odys packagekitd[1822]: http://apt.pop-os.org/release jammy/main amd64 firefox amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
sep 27 08:50:16 odys packagekitd[1822]: http://apt.pop-os.org/release jammy/main amd64 pop-default-settings all 5.1.0~1663192506~22.04~5c9bcd8 is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
sep 27 08:50:16 odys PackageKit[1822]: update-packages transaction /3060_ababccac from uid 1000 finished with failed after 2794ms
sep 27 08:50:16 odys io.elementary.a[19801]: Package.vala:577: Operation failed for package Operating System Updates - E: http://apt.pop-os.org/release jammy/main amd64 pop-launcher amd64 1.2.1~1662488179~22.04~6e2fa02 is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
                                             E: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-ar amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
                                             E: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-zh-hant amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
                                             E: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-zh-hans amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
                                             E: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-ru amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
                                             E: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-pt amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
                                             E: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-ja amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
                                             E: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-it amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
                                             E: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-fr amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
                                             E: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-es amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
                                             E: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-en amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
                                             E: http://apt.pop-os.org/release jammy/main amd64 firefox-locale-de amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
                                             E: http://apt.pop-os.org/release jammy/main amd64 firefox amd64 104.0.2~1662490162~22.04~faed4ab is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
                                             E: http://apt.pop-os.org/release jammy/main amd64 pop-default-settings all 5.1.0~1663192506~22.04~5c9bcd8 is not (yet) available (404  Not Found [IP: 143.204.9.94 80])
sep 27 08:50:16 odys io.elementary.a[19801]: g_value_get_pointer: assertion 'G_VALUE_HOLDS_POINTER (value)' failed
sep 27 08:50:16 odys kernel: io.elementary.a[19801]: segfault at 8 ip 000055fe686cbde1 sp 00007ffd3d082590 error 4 in io.elementary.appcenter[55fe68695000+67000]
sep 27 08:50:16 odys kernel: Code: c6 fc ff 48 89 e9 48 89 ef 48 8d 15 59 96 ff ff 45 31 c0 48 8d 35 f4 0a 03 00 e8 ea f6 fc ff 48 8b 45 50 48 89 ef 48 8b 40 08 <48> 8b 70 08 e8 06 f6 fc ff 48 83 c4 08 4c 89 e0 5d 41 5c 41 5d 41
sep 27 08:50:17 odys systemd[1300]: app-gnome-io.elementary.appcenter-19801.scope: Consumed 6.145s CPU time.
``` 

I double checked and `apt.pop-os.org` resolves properly and even setting it to another of its valid IPs in my `/etc/hosts/` file didn't solve the issue. (It seems to be a 301 redirect, but I guess it's normal)

**Steps to reproduce (if you know):**

Maybe setting an invalid IP for `apt.pop-os.org`? Not sure what's going on here.

**Expected behavior:**

For it to work. 
Segfaulting seems bad.

**Other Notes:**

It seems my `apt` was locked by the auto-updater:

```
$ sudo apt-get update
Reading package lists... Done
E: Could not get lock /var/lib/apt/lists/lock. It is held by process 2444 (apt-get)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to lock directory /var/lib/apt/lists/

$ ps aux | grep 2444
root        2444  0.0  0.0  28852  9612 ?        SN   07:52   0:00 apt-get update
```

After killing it and re-trying it worked... I'm finding it weird the auto-updater isn't somehow timing out after 10-15 minutes...

So, I guess this bug is two-fold:
- It segfaults on 404.
- It errors out with a 404 when there's a weird deadlock somewhere else that made apt-get freeze upon boot.

### LINKED ISSUE #395: SIGSEV when cache is broken
**Distribution (run `cat /etc/os-release`):**
```sh
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```sh
pop-shop:
  Installé : 3.4.2pop0~1663946596~22.04~3f71ef4
  Candidat : 3.4.2pop0~1663946596~22.04~3f71ef4
 Table de version :
 *** 3.4.2pop0~1663946596~22.04~3f71ef4 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
Pop shop does not start

**Steps to reproduce (if you know):**
Fill up your disk, maybe?

**Expected behavior:**
Start pop-shop.

**Other Notes:**
`strace io.elementary.appcenter` ends with 
```
access("/home/zykino/.cache/io.elementary.appcenter/flatpak-metadata/user/icons/flathub/64x64/org.sugarlabs.SolarSystem.png", F_OK) = 0
access("/home/zykino/.cache/io.elementary.appcenter/flatpak-metadata/user/icons/flathub/128x128/org.sugarlabs.SolarSystem.png", F_OK) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7f9c3bea7000} ---
+++ killed by SIGSEGV (core dumped) +++
fish: Job 1, 'strace io.elementary.appcenter' terminated by signal SIGSEGV (Erreur de frontière d'adresse)
```
(SIGSEGV: Address boundary error)

So I did `rm ~/.cache/* -r` and now pop-shop start again.

Before that I tried : `sudo apt --fix-broken install` and `sudo apt install --reinstall pop-shop` without success.

### PR DESCRIPTION
**Pull request by mmstick**
This looks like a compiler bug in Valac. The object is initialized with the error property defined, but the program crashes in the constructor because it's accessing a field that's not initialized.

The crash can be replicated by having some updates available, modifying `/etc/hosts` with

```
127.0.0.1       apt.pop-os.org
```

And then clicking Update All on the Installed tab.

Closes #395 
Closes #393 
Closes #386 
Closes #387 
Closes #381 
Closes #356 
Closes #358  
Closes #341
Closes #353

### CODE REVIEW

**Review by 13r0ck — APPROVED** [review]

**Comment by jacobgkau** [comment]
A number of these are difficult to recreate on demand. I have confirmed this fixes https://github.com/pop-os/shop/issues/393 -- When `apt.pop-os.org` is set to resolve to the loopback address in `/etc/hosts`, I now get `Failed to update "AppName"` instead of a crash.

This does not fix https://github.com/pop-os/shop/issues/353 -- I still get a crash when attempting to uninstall the preinstalled Vim. Is this supposed to fix that, or should it be removed from the list?

**Comment by mmstick** [comment]
Can investigate the vim issue separtely

**Comment by mmstick** [comment]
Actually, maybe I'll add a quick patch for the other error dialogs. It's possible that it's the same kind of memory safety violation.

**Comment by mmstick** [comment]
This commit should fix the error dialogs when uninstalling packages

**Review by jacobgkau — APPROVED** [review]
Attempting to uninstall Vim now shows a `Failed to uninstall "Vim"` dialogue box instead of crashing. The `/etc/hosts` case is also still working.

**Comment by jacobgkau** [comment]
Regression testing checklist also passed:

 - [X] Search works on the main page and inside a category
 - [X] Search bar is useable without requiring explicit focus on both the Home and any Catagory page
 - [X] Installing a new application and uninstalling it works
 - [X] Viewing installed applications from the Updates menu works
 - [X] Right clicking on applications in GNOME Shell and clicking on "Show Details" works for programs with appstream data
 - [X] Pop!_Picks display in a random order
 - [X] Swipe gesture goes back from an app listing or category
 - [X] `Ctrl`+`R` Refreshes Apt Cache and Flatpak Metadata
 - [X] `Crtl`+`S` Opens Software Sources (repoman)

**Review by 13r0ck — APPROVED** [review]
I believe that this should be up-streamed as well.

**Comment by mmstick** [comment]
Done https://github.com/elementary/appcenter/pull/1936

**Pull request merged**
