### PR TITLE
fix: Fix ubuntu-drivers and show available NVIDIA drivers

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by jackpot51 — CHANGES_REQUESTED** [review]
This shows the drivers but we still need to filter out drivers ending in -server

**Review by jackpot51 — APPROVED** [review]

**Review by jackpot51 — CHANGES_REQUESTED** [review]
I missed this before, even if a driver has been installed, it shows up with an install button under Drivers

**Review by jackpot51 — APPROVED** [review]

**Comment by XV-02** [comment]
Pop!_Shop now displays an option for driver install under the "Installed" tab. It lists the driver version to be installed, and successfully installs the driver. In testing, this was driver version 390, which does not successfully suspend in 21.10. With the driver installed and nvidia-smi and the Nvidia X Server Settings application launches correctly.

**Comment by jackpot51** [comment]
@XV-02 I believe that https://github.com/pop-os/nvidia-graphics-drivers/pull/136 is required to be merged and released before it will show the 470 driver. This is because currently the released 510 driver provides the 470 driver as virtual packages

**Comment by XV-02** [comment]
Pop!_Shop shows and installs the 390 and 470 drivers as options, and successfully uninstalls 510 when installing those drivers.

**Comment by mmstick** [comment]
We ready to merge then?

**Comment by XV-02** [comment]
Pop!_Shop correctly displays Nvidia drivers for install, correctly installs said drivers and removes other drivers if present.

**Review by XV-02 — APPROVED** [review]
No evidence of broken features, and desired functionality works.

**Pull request merged**
