### PR TITLE
Welcome banner

### PR DESCRIPTION
**Pull request by cassidyjames**
screenshot from 2018-03-14 12-02-45

Two known bugs, but I don't think they're blocking:
- [ ] When resizing, the background of the labels sometimes doesn't update. 
- [ ] The second line of text is lower than is should be. When setting or modifying the same properties in the inspector, it works fine. But when it's compiled in, it's too low.

Both look like GTK bugs, but I don't know how to work around them.

### CODE REVIEW

**Comment by cassidyjames** [comment]
There's currently a bug with the pop_banner _copy_1 vexpand or something; if I mess with it in the inspector, it's all good, but if I do it in code, it expands too much.

**Comment by isantop** [comment]
Looks good. @WatchMkr wants to have the "NEW" removed.

**Comment by isantop** [comment]
@brs17 Please do a standard review on this and ensure that the new version shows the banner.

**Comment by isantop** [comment]
Whoops, this should not be closed.

**Comment by brs17** [comment]
The `welcome-banner` branch totally breaks the categories in the Pop!_Shop. And none of the categories are clickable.

screenshot from 2018-03-15 09-09-56

**Comment by cassidyjames** [comment]
@brs17 commit 47c8afd from @isantop missed a closing brace, which murdered the CSS. Fix committed.

**Comment by brs17** [comment]
Looks like the word `Categories` is at the bottom of the Pop!_Shop. (artifact from elementary app center)

Also clicking on any of the categories does not work, only selecting <kbd>tab</kbd> and hitting <kbd>enter</kbd> works.

**Comment by brs17** [comment]
I also noticed that the headerbar is much wider than it was previously. Are we ok with this? It seems super large.

**Comment by cassidyjames** [comment]
>I also noticed that the headerbar is much wider than it was previously.

That's from the sync from upstream, not this branch. @isantop might want to take a look at the CSS for that.

**Comment by cassidyjames** [comment]
Alright, I've fixed the homepage attachment. But now there's some other completely unrelated build error that I'm going to take a look at…

**Comment by cassidyjames** [comment]
_Sigh._ Something I just noticed is that somehow it's not checking for updates when you open it any more. I think there was likely a callback in the old banner code that checked for updates. Investigating…

**Comment by cassidyjames** [comment]
@brs17 @isantop this is ready for re-review. I initially pulled a bunch of unused things out, but it broke in strange ways, so I've restored most of it.

If we add a Pop!_Picks in the future, we'll need to do some more work here (and there are some widgets being created that are explicitly never attached to the window), but I think this delivers the wanted feature with the least refactoring of upstream code.

**Pull request merged**
