### PR TITLE
Upstream rebase

### PR DESCRIPTION
**Pull request by isantop**
Upstream Appcenter has had many nice changes since the last time we synced up; this pulls in the latest updated code from AppCenter to bring these new developments into Pop_Shop.

Improvements Include: 
* Improvements to asynchronous processing to improve performance and reduce UI blockages.
* Redesigned top-bar which improves use with narrow form factor windows and better highlights search functionality.
* Fixes for issues related to "Open" button for newly-installed Apps
* Reductions in changes from upstream, simplifying future maintenance.
* Status overlay to better communicate background progress

### CODE REVIEW

**Comment by mmstick** [comment]
I get a segmentation fault the moment it finishes fetching download sizes while loading packages for a category. I'll run it through gdb and try to find out why a gobject is being unref'd once too many times.

**Comment by mmstick** [comment]
The root of the problem is a thread safety violation between the main thread and the flatpak backend.

**Comment by mmstick** [comment]
There's still an occasional crash on the main page that happens at random involving a pango layout being `NULL`. Looking around there's a lot of thread safety violations so it might be caused by one of them.

**Comment by mmstick** [comment]
Seems to be fixed now. The homepage now waits for the packagekit and flatpak threads to finish before it starts adding packages to the carousel. And the Ubuntu drivers backend also waits for the packagekit thread to finish before it does its work.

**Comment by isantop** [comment]
@mmstick I'm now getting a segfault any time I try and open the application: 

```
io.elementary.appcenter

(io.elementary.appcenter:25102): Gtk-WARNING **: 08:36:04.006: Theme parsing error: application.css:42:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.
[1]    25102 segmentation fault (core dumped)  io.elementary.appcenter
```

**Comment by mmstick** [comment]
They happen at random. There's still several instances of shared memory in a thread race

**Comment by mmstick** [comment]
Every search seems to cut off the first few characters that were typed

**Comment by isantop** [comment]
It appears that as of caf11a86051b4c98e3ff0a0200f72fd4f5e517ed I'm getting a segfault every time the app opens.

**Comment by ids1024** [comment]
I don't see a segfault, but valgrind does indicate a couple memory errors: https://gist.github.com/ids1024/49f4a23aa55c4969b95228e861b13642

(Pop shop takes a long time to start in valgrind. `AddressSanitizer` should be faster if you can get it to build with it.)

**Comment by isantop** [comment]
In my testing I'm able to reproduce this reliably when starting the application from scratch; it segfaults on every run when opening while not running in daemon mode. If the XDG Autostart service opens Pop Shop in daemon mode, it opens correctly and can be used as normal

**Comment by isantop** [comment]
I can definitively reproduce this using the following procedure: 

1. Use `killall io.elementary.appcenter` to ensure Pop Shop is not running.
2. Ensure that caf11a8 is installed via staging apt branch
3. Run `io.elementary.appcenter` to launch a new instance of Pop Shop
4. App will crash when loading the window.

**Comment by isantop** [comment]
@ids1024 Running Pop_shop with either Valgrind or AddressSanitizer seems to prevent whatever race condition is causing the segfault. It does still crash if run with gdb (and compiled with debug symbols)

**Comment by isantop** [comment]
I believe I've worked around the segfault I was getting as of 06a26c6 but would appreciate another check

**Review by jacobgkau — COMMENTED** [review]
After updating and rebooting, I am seeing the Pop!_Shop take about 10 seconds to open and another 5 seconds before the `"Pop!_Shop" is not responding` dialogue goes away. There are a few seconds between when I launch and when the dock shows the app as "running," even before the window appears. The times are consistent; if I close the window and re-open it immediately after, it still takes that long to start.

Before this update, the same system shows the window open immediately after launching, so this seems like a regression.

**Comment by isantop** [comment]
> After updating and rebooting, I am seeing the Pop!_Shop take about 10 seconds to open and another 5 seconds before the `"Pop!_Shop" is not responding` dialogue goes away. There are a few seconds between when I launch and when the dock shows the app as "running," even before the window appears. The times are consistent; if I close the window and re-open it immediately after, it still takes that long to start.
> 
> Before this update, the same system shows the window open immediately after launching, so this seems like a regression.

It might be possible to reduce the delay before the window opens, but a lot of the delay is related to setting up the async processing (which has to happen with locks in place to prevent segfaults like those already discussed in this thread) which wouldn't be possible to fix without major changes (i.e. rewrites) from upstream. It's worth noting that a lot of this processing also had to take place with the previous version, but because there was less asynchronous processing the application window would lock instead. 

One other point to consider; on my system loading the currently-release version of Shop takes approximately 4 seconds from a cold start. It opens instantly if the daemon has been started (i.e. with `--silent`), but that's because the loading has taken place already. Ensure that Shop has closed completely (`killall io.elementary.appcenter`) in both cases before comparing performance between versions, as this branch also opens quickly after rebooting (since it will start in the background instead of the old version).

**Comment by mmstick** [comment]
I've done a lot of installing, reinstalling, and applying updates since yesterday and this morning. I've not been able to reproduce any crashes from before. Sometimes a category is a bit slow to load, and one of the locks can cause the UI to block for 5-15 seconds until a thread has finished its task, but other than that it's a significant improvement and resolves thread-safety issues in the current release.

Further improvements will likely require substantial changes to the code. The easiest improvement might be using an async variant of a mutex, using either the AsyncMutex class in the repository or making a custom one with a thread and callback. But it'd require altering every function containing an async mutex to be async too.

The biggest improvement would be to ensure that all GObjects touching anything GTK-related are only scheduled and only interacted with from the global default glib main context, but the data seems very tightly coupled with their GTK widgets so that'd require a radically different architecture separating the data from the widgets.

**Review by mmstick — DISMISSED** [review]

**Review by 13r0ck — COMMENTED** [review]
I would like QA to double check me, but If I open pop shop with this, then use the search bar on any page other than home the app completely freezes and I have to force quit it.
I know that previous versions of pop shop just disabled search on pages that weren't the home page.

**Comment by maria-komarova** [comment]
Can't do it right now but will take a look tomorrow morning.

**Comment by maria-komarova** [comment]
Looking at the changes, the feedback from @jacobgkau seems very relevant. 
- If possible, it would be much better to have the Uninstall and Open buttons be next to each other instead of stacked since it makes the UI look unpolished and gets visually in the way of the user. 
- It would also be better to have a label inside of the button for Installed apps. Maybe having the button with a label "Installed" with the number overlay for the updates, the way it works now, instead of the icon button, would be enough to improve usability. The icon in the updated design is too vague to be easily recognizable and while the tooltip helps a little, it does not seem sufficient for the easy discovery of this important app functionality. 
- Install UX as described by @jacobgkau does seem to be a regression. 

Let us know if we should look at anything else.

**Comment by isantop** [comment]
Having the label inside of the button for Installed Apps will cause the window to automatically expand when it's being displayed at very narrow sizes due to the way hiding and showing both the Installed Apps and Back buttons works. In order to prevent this, it would be required to set a larger minimum size for the window, which could affect tiling usability.

**Comment by isantop** [comment]
Another alternative might be using a different, symbolic icon, which better matches the rest of the Pop UI/UX. That would also be a significantly smaller change from upstream, which makes future maintainability much easier.

**Comment by isantop** [comment]
It looks like I can fit "In" before the button grows in size and begins limiting the minimum width. The button would need to be as narrow as possible (down to just being the same width as its height). 

Here's a screenshot using the symbolic icon; it could also be a different icon in our set: 

image


One other option I just considered was moving the entire button to the menu with a text item. That would also allow for a keyboard shortcut, which could be faster. Since we now have the option for automatic updates, I suspect that using the installed view is going to be much lower priority going forward, so that could simplify the top bar quite a bit and possibly allow for an even narrower window width.

**Comment by maria-komarova** [comment]
It might be an option although it is still less discoverable. It might then be better as an item below the header area but that would be even more of a patch.

**Comment by isantop** [comment]
> It might be an option although it is still less discoverable. It might then be better as an item below the header area but that would be even more of a patch.

@maria-komarova I'm not sure what you mean by below the header?

**Comment by maria-komarova** [comment]
Sorry for not being clear. I meant below the banner image with Unleash your potential. But it doesn't necessarily fit there as naturally. And more of a patch.

**Comment by isantop** [comment]
Apt packages should now be fixed as of 35ac918

**Comment by isantop** [comment]
> Sorry for not being clear. I meant below the banner image with Unleash your potential. But it doesn't necessarily fit there as naturally. And more of a patch.

@maria-komarova I definitely agree it doesn't fit there. 

The more I think about it, the more I think that putting it into the menu makes sense. With the new updates system provided by Pop Updates, the Installed Apps page has very little actual use in Pop Shop, so I think putting in the slightly less discoverable place in the name of preserving our existing usability makes sense.

**Comment by maria-komarova** [comment]
To clarify, what is the functionality that;s now left in the Installed section?

**Comment by isantop** [comment]
> To clarify, what is the functionality that;s now left in the Installed section?

I think the primary functionality is for quickly getting to apps that you have installed, e.g. to uninstall them. I do think it's helpful to be able to quickly list all installed applications, and I think that appears to pan out by the universal presence of such a list in other platforms' store interfaces as well. It does appear that it's very common for other store interfaces to place the access to such a list within a hamburger menu, so I don't think the discoverability is actually that low there. I think that since elementary currently uses Appcenter as an interface not just for installing applications but also as the primary system update location, the more prominent positioning there makes sense, but since we've offloaded that function in Pop it might be more beneficial in our case to declutter the top bar, especially since the new search bar takes up so much space.

**Comment by isantop** [comment]
I've set up what this type of thing could look like. I'm not tied to the "Installed Apps" text; perhaps "Installed Software" works better?

image

**Comment by jacobgkau** [comment]
> The more I think about it, the more I think that putting it into the menu makes sense. With the new updates system provided by Pop Updates, the Installed Apps page has very little actual use in Pop Shop,

I want to point out that auto-updates are disabled by default and not all users will enable them. The updating functionality in the Pop!_Shop is still just as relevant for those users as it was previously, regardless of the auto-updater.

**Comment by isantop** [comment]
Ah, I was under the impression that the updater was still handling the updates even with auto updates disabled.

I can put the updater badge on the menu button, which should still aid discoverability for that important function.

**Comment by isantop** [comment]
And here we are with the Updates Badge on the menu button: 

image

**Comment by maria-komarova** [comment]
Thanks. That might be an option but we still worry about it being easy to understand how to find installed apps. Would it be possible to see how narrow we can get the window with the button with a label? Just want to see what it looks like before making the final call.

**Comment by isantop** [comment]
With an installed apps button and a label set to "Installed & Updates", the home page can shrink to a minimum width of 467 pixels, and grows to a width of 567 when opening any item from the home page.

Screenshot from 2023-02-08 10-55-36 Screenshot from 2023-02-08 10-53-52 

With the label set to only "Installed", the window can shrink to a minimum of 400 px, but grows to 500 pixels upon opening any item:

Screenshot from 2023-02-08 10-59-48 Screenshot from 2023-02-08 10-59-58
I also don't feel that just the word "Installed" really conveys what the button does either, requiring the user to experiment by pressing the button anyway to discover the functionality. 


For tiling compatibility, Pop Shop currently has a hard-maximum for it's minimum width of 480 pixels (one quarter of the width of a 1080p display, 1920/4), so the extra width does not work with the current design goals. Without a button, the widest the window needs is 424 pixels, which does fit within the limits.

Screenshot from 2023-02-08 11-05-03

**Comment by isantop** [comment]
One other thing to note is that the label tends to be shorter in English. If a user has their locale set to a different language where that string is translated, it will often further expand the window width. For example, in Swedish the string might be "Installerad", Spanish could be "Instalado", and German could be "Eingerichtet", all of which would increase the minimum width significantly.

**Comment by jacobgkau** [comment]
I'm not understanding why the minimum width has to grow when an item is selected vs. the home page, only when the button has text in it. The button having text and what's in the rest of the window don't seem related. Is that just a separate bug?

**Comment by isantop** [comment]
> I'm not understanding why the minimum width has to grow when an item is selected vs. the home page, only when the button has text in it. The button having text and what's in the rest of the window don't seem related. Is that just a separate bug?

It grows because the button doesn't hide at the same time as the back button being shown, which means that space needs to be allocated for the back button, the search bar, the Updates button, and the menu button all simultaneously, like so: 

image

(They wouldn't normally be actually visible at the same time, but because of the way GTK packs widgets there can be space allocated for them without them being visible yet/anymore)

**Comment by 13r0ck** [comment]
Just to throw i my two cents, I prefer https://github.com/pop-os/shop/pull/401#issuecomment-1422933022 I see no benefit for showing a separate updates button that disappears when less than a specified width.
It seems like it could be more confusing to have the button "randomly" disappear. I would rather have the one place to go to for updates, and have it always there.

**Comment by maria-komarova** [comment]
> ... a separate updates button that disappears when less than a specified width.

I didn't realize a button would disappear. We were always talking about Installed button as being permanently in the header. 

@isantop thanks a lot for clarifying the situation with the window width, it helps to better understand the context. 
From everything that has been said it looks like Installed Apps in the Hamburger menu with the badge might be our best bet right now. 
Wonder if it might be helpful to have it as the first item separated from others with the divider and with the same number badge to indicate what item in the menu the badge belongs to. We can probably say "Installed Apps & Updates" with the number badge going in the top right corner of the word Updates. And maybe keep Check for Updates instead of Refresh.

**Comment by isantop** [comment]
To be clear, the button would not disappear. That was a misunderstanding on Brock's part, which I cleared up irl. The button would be a permanent part of the headerbar.

For the updates badge, I think having two of them in such close proximity would be too cluttered/redundant. What about setting an alternate background color on that item?

I can move the Updates item first in the list and add a separator.

**Comment by maria-komarova** [comment]
It might look cluttered but I don't think it would be redundant. Changing the background might not be enough to understand how one relates to another. An alternative might be to not have a keyboard shortcut and show the badge at the end of the line instead of the keyboard shortcut.

**Comment by isantop** [comment]
@maria-komarova Actually, it looks like GTK doesn't want to let me add the updates badge to the menu as well. It doesn't seem to like overlay widgets the same way as the headerbar, and is not showing either way. 

I did do a quick and dirty look of what it looks like with the item background changed. A different color could also work; this just matches the color to the badge color, to help tie the two together. I have not yet moved it to the top, nor added the separator:

image

**Comment by isantop** [comment]
Updated to get the order/spacing correct: 
image

**Comment by isantop** [comment]
Maybe limiting the background to the label:

**Comment by isantop** [comment]
Maybe limiting the background to the label: 

image

**Comment by maria-komarova** [comment]
Can work if the background is the same color as the badge. I like it more when it includes the shortcut.

**Comment by isantop** [comment]
@maria-komarova  So the current iteration is as follows:
Screenshot from 2023-02-08 15-50-29
-f3f9eed4-5dd9-4b1a-9926-1fb2750d75c5.png)

@13r0ck brought up a good point that we currently use red highlights for destructive actions, whereas green is used for suggested actions. In light of this, we thought about changing both the badge and the background to green?

**Comment by isantop** [comment]
@maria-komarova One other point: I think that the term "Installed Software" is more appropriate than "Installed Apps" since there is also OS-level and under-the-hood runtime software in that page. I believe "Software" is inclusive enough to indicate "Apps".

**Comment by maria-komarova** [comment]
Sure, software sounds good then if width is not a concern.

**Comment by hojjatabdollahi** [comment]
I am using the PopShop build from  `pop-shop 3.4.2pop0~1675897810~22.04~4194559` and it crashes a lot.  Out of 40 tries, 8 of them segfaulted.

One time it crashed because I was changing the window size while it was refreshing the database:
```
io.elementary.appcenter: ../../../../src/cairo-region.c:428: cairo_region_destroy: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&region->ref_count)' failed.
zsh: IOT instruction (core dumped)  io.elementary.appcenter
```
Once it crashed with:
```
malloc(): unaligned tcache chunk detected
zsh: IOT instruction (core dumped)  io.elementary.appcenter
```
The other 6 times it would not even show the window and only print this:
```
zsh: segmentation fault (core dumped)  io.elementary.appcenter
```
I couldn't find the exact place that it crashes but using gdb I found this:
```
Thread 13 "flatpak-worker" received signal SIGSEGV, Segmentation fault.
```

**Comment by jacobgkau** [comment]
Installing and removing both .debs and Flatpaks seem to be working for me now. Still testing for stability.

**Comment by jacobgkau** [comment]
@isaac-8601 We notify the user about installed updates with the badge on the hamburger menu. (We also do have pop-upgrade send _notifications_ for updates weekly by default, it just doesn't actually install them by default; those notifications should open the Pop!_Shop to the correct page.)

It sounds like having a button that just says `Updates` on the headerbar would also introduce some of the same drawbacks as one that just says `Installed`, since those words aren't very different in length.

> but in the future maybe we consider another view that has exclusively updates?

I'm not sure how much value this would add, but it seems like something we would consider if/when we replace the Pop!_Shop/AppCenter, rather than as a patch. @isantop can let me know if I'm wrong (I don't know how easy/difficult it would actually be to split those out.)

**Comment by isantop** [comment]
Yeah, separating Updates from the Installed Apps list is not something that's feasible with the current codebase. There's a possibility to add a separate view which only lists available updates, but it would duplicate functionality already present in the Installed Apps view. Basically, because the installed apps view has the buttons to do the updates (and the updates are a pretty minimal UI on top of that page), I don't think that separating them makes a lot of sense. Basically you have the Installed Apps which is a list of installed apps, and then Updates which would be a list of Installed Apps that have updates available. It doesn't feel like a meaningful difference to me.

**Comment by jacobgkau** [comment]
I'm not seeing the hamburger badge and highlighted menu entry when I have an update available:

Screenshot from 2023-02-10 10-35-50

If I kill `io.elementary.appcenter` and restart it, then I do see those things:

Screenshot from 2023-02-10 10-38-06

Closing it again and launching with `-s` and re-opening, I don't have them anymore. @isantop Any idea what's going on with this?

It also sounded like we wanted the highlight to extend around the entire hamburger menu entry (including the keyboard shortcut), not just the text label, based on https://github.com/pop-os/shop/pull/401#issuecomment-1423293610.

**Comment by maria-komarova** [comment]
The more I look at it the more awkward the background behind the label looks. I wonder if it would be better (and possible) to have the badge not as an overlay but as content in place of the shortcut. I'm not sure how much value the keybinding offers compared to having good experience with the updates indicator that feel integral to the UI in general. 
pop-shop-quick-mock
It's not ideal but it would be better than the background behind the label.

**Comment by isantop** [comment]
@maria-komarova I was able to add the badge as you had it in the earlier image:

After updates have loaded


Additionally, I was able to make it so that they can switch between the badge and the shortcut; the menubadge will be displayed whenever there are updates available, otherwise it will display the shortcut. I think this aids with discoverability for the shortcut while still prioritizing the menubadge whenever an update is available:

Before Updates have loaded

**Comment by maria-komarova** [comment]
Great! Thanks, I think it might be the best compromise under the circumstances.

**Comment by hojjatabdollahi** [comment]
Is this behavior intentional:

If you type 3 letters in the search box, it will show the results, if you press backspace and delete the last letter (now you have two letters in the search box) it will cancel everything, clear the box and take you back home.

**Comment by jacobgkau** [comment]
@hojjatabdollahi I can replicate this. Seems like it only happens when there are 2 characters left, no matter how many characters were typed first. Similarly, searches don't take effect until the third character is typed.

This seems semi-intentional, but it also seems quirky. However, the current Pop!_Shop also works like this, so it's not really a regression. (The change in behavior from the current version is that the search box now automatically searches when 3 characters have been typed; previously, you had to press Enter to search, and that did nothing if only 1 or 2 characters were typed.)

**Comment by hojjatabdollahi** [comment]
@jacobgkau Makes sense. It's not a big deal. BTW I can also replicate the issue you described [here](https://github.com/pop-os/shop/pull/401#issuecomment-1426133857).

**Comment by isantop** [comment]
With less than 3 characters, the search results can be too large to prevent performance issues with Shop, so they're cut off below 3.

**Comment by jacobgkau** [comment]
The in-app update badge is still not working with the shop running as a daemon before opening the window.

Screenshot from 2023-02-13 15-01-46

Just wanted to clarify that's still happening. (Also, not sure if it would be possible to change the color of the in-dock badge to match the in-app badges-- it's okay if it's not.)

**Comment by isantop** [comment]
> Also, not sure if it would be possible to change the color of the in-dock badge to match the in-app badges-- it's okay if it's not.

These are set by the Gnome Shell theme, so it's not possible to change them. We might be able to set our shell theme to hardcode an exception for Pop Shop, but I'm not particularly comfortable with that.

**Comment by isantop** [comment]
I can't seem to replicate the Daemon-Badge issue: 

image

Testing methodology:

In Terminal 1:
```
killall io.elementary.appcenter # Ensure a clean testing environment
io.elementary.appcenter -s # Start daemon mode
```

In Terminal 2:
```
io.elementary.appcenter # Open the window
```

Results:
The update badge appears correctly.

**Comment by 13r0ck** [comment]
If we are doing the notification bubble as a bubble in the drop down too, then maybe just keeping the red universally is the right idea for consistency. A red indicator and a red button mean very different things, to me at least

**Comment by jacobgkau** [comment]
@isantop Thanks for the methodology. I narrowed the issue down further; apparently, it's not just about whether the shop is running in daemon mode or not, but whether the icon is used to launch it or not. After starting it in daemon mode, I get the badge when running `io.elementary.appcenter` from the terminal, but not when starting it from the icon.

Here is a video demonstrating this (from a fresh boot/login):

https://user-images.githubusercontent.com/7199422/219483780-010fe913-1439-4986-9966-bd0a1d4ac242.mp4

If I kill the daemon and then launch from the icon, then I _do_ get the badge. So the steps to recreate are:

1. Ensure the shop has been started in daemon mode.
2. Open the shop window _using the icon._

**Comment by isantop** [comment]
Alright, I'll take a look at it. So nice of it to have a problem that doesn't happen where I can see log output. 😛

**Comment by isantop** [comment]
After testing the stability of Pop Shop by running it 1000 times, I've observed a total of 45 crashes for an overall stability of 95.5%. While I think this could definitely be improved, I don't personally think this is low enough to be considered a major regression, and given the other benefits that this branch brings, I think it would be acceptable to merge this to start and improve the stability later.

I will need to look into the update notification issue first.

**Comment by isantop** [comment]
@jacobgkau It looks like the updates badge revealer was being triggered when the number of updates changes. On the problematic version, I believe opening Shop via the icon would allow the badge to show the first time it was opened, but as you noticed, subsequent opens will not show the badge.

This is fixed in f84643b by adding a change to the updates number property to the refresh method, which should then trigger the badge whenever there's a cache update and updates are available. This may cause the badge to briefly hide then reshow in certain circumstances, but I think that tradeoff is okay given that we want to ensure that the badge is always showed when updates are available.

**Comment by isantop** [comment]
This is where we're currently at (the specific red in the menu will update based on dark mode or light): 

image

**Comment by jacobgkau** [comment]
Small regression. When clicking `Show Details` from the Applications menu if the Pop!_Shop is not already open, then the shop only opens to the Installed page, not to the application's page. It does open to the application's page if the shop was already open.

On the previous Pop!_Shop, the shop opened to the application's page when this button was clicked even if it wasn't already open.

**Comment by isantop** [comment]
> Small regression. When clicking `Show Details` from the Applications menu if the Pop!_Shop is not already open, then the shop only opens to the Installed page, not to the application's page. It does open to the application's page if the shop was already open.

@jacobgkau I'm having a hard time replicating this issue. Even if I kill the Pop_Shop process first, when I use Show Details the shop correctly opens the app in the list. Running 4991fb9 installed via apt (through the `upstream-rebase` staging branch). Which app are you seeing issues with? There might be some other factor causing that problem.

**Comment by jacobgkau** [comment]
@isantop Sorry, I've narrowed it down to Flatpak apps. Kdenlive is an example app that is affected. To clarify, the process being started/stopped doesn't affect this; it's actually whether the window is open to the Installed page specifically that determines whether it works (if it's open on another page, the first attempt opens up the Installed page, similar to if the window was closed.) See below:

https://user-images.githubusercontent.com/7199422/223559971-aa3fe467-5513-420c-a1b3-a28cc3e3eff3.mp4

Some other Flatpak apps, such as VS Code or LibreOffice (when installed via Flatpak), do not work even if the window's already open. That is _not_ a regression. But Flatpak apps that used to work (such as Kdenlive) should continue to work on the first try after the update.

**Comment by isantop** [comment]
So, I'm getting a slightly different problem in my testing:

[kdenliv.webm](https://user-images.githubusercontent.com/5883565/225082423-bda382f0-499a-4c68-9627-75e00a577b6d.webm)

Shop reliably opens the App details for me. There is often a large delay between clicking on "Show Details" and opening Shop, though.

**Comment by jacobgkau** [comment]
@isantop I tried testing on a different system. I found that at first, clicking `Show Details` on Kdenlive (in the App Library or the App Library's search results) didn't recreate this issue. However, I went to `Installed`, closed the shop, and then the issue started occurring. It continues to occur even if I go back to `Home`, close, and try again. Can you try navigating to the `Installed` page before closing the window and then seeing if the issue occurs?

**Comment by isantop** [comment]
I think I figured out what was causing that. It should be fixed as of b4c91ae

**Comment by jacobgkau** [comment]
The `Show Details` bug is fixed. I see a slight delay sometimes, but I don't consider that blocking.

It does seem like a similar issue occurs with opening the shop using the icon, though. If I go to Installed, back to Home, close, and click the icon, it opens to Installed. Can the fix be applied to icon launching as well?

**Comment by isantop** [comment]
> The `Show Details` bug is fixed. I see a slight delay sometimes, but I don't consider that blocking.
> 
> It does seem like a similar issue occurs with opening the shop using the icon, though. If I go to Installed, back to Home, close, and click the icon, it opens to Installed. Can the fix be applied to icon launching as well? (Even if this ends up making it so closing from Installed no longer opens it back to Installed, I still think defaulting to Home would be more reasonable behavior than defaulting to Installed after explicitly navigating back to Home.)

No, because the icon opening is handled exclusively with the `activate()` method, whereas opening to the Installed Page (which is how the update notification works) uses the show_updates_action (which the notification uses) calls as part of its usage. 

I will point out that I've also occasionally seen that issue for years (typically after opening the updates page from the notification) so I'm not sure if that's a regression.

**Comment by isantop** [comment]
I believe the issue is due to underlying architecture changes with the new version of Pop Shop. Large parts of this class are very different from the current version.

**Comment by isantop** [comment]
76c2bbe includes a change which resets the flag telling Shop to open to the Installed page once the window is activated. It should still open to the Installed page when it's triggered for that, but afterwards it is reset so that it stays on the home page. There may still be isolated incidents where the window incorrectly presents the Installed page, but subsequent opening should resolve this (i.e. it won't get stuck opening to the Installed page anymore).

**Comment by jacobgkau** [comment]
76c2bbe is an improvement. The shop now always seems to open to Home. However, running `io.elementary.appcenter -u` or `io.elementary.appcenter --show-updates` only opens the Installed page if the shop's daemon was not already running. Should that work if the shop's already running in the background?

(Separately, the notifications from `system-updater` don't seem to open the Pop!_Shop at all; I have confirmed that is *not* a regression. But we still want the shop to have the ability to open to Installed so that can be fixed in `system-updater` later, if it's not a Pop!_Shop issue.)

I also seem to be getting more shop crashes now. It seems to happen a few seconds after opening the window sometimes. I just got a segfault, for example:

```
Mar 16 15:01:00 pop-os io.elementary.a[2880]: pango_layout_is_wrapped: assertion 'layout != NULL' failed
Mar 16 15:01:00 pop-os io.elementary.a[2880]: pango_layout_is_ellipsized: assertion 'layout != NULL' failed
Mar 16 15:01:00 pop-os io.elementary.a[2880]: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
Mar 16 15:01:00 pop-os io.elementary.a[2880]: pango_layout_get_extents: assertion 'layout != NULL' failed
Mar 16 15:01:00 pop-os kernel: show_signal_msg: 12 callbacks suppressed
Mar 16 15:01:00 pop-os kernel: io.elementary.a[2880]: segfault at 110 ip 00007f22f68a3d79 sp 00007fffb1d93b60 error 4 in libc.so.6[7f22f6828000+195000] likely on CPU 2 (core 1, socket 0)
Mar 16 15:01:00 pop-os kernel: Code: 3b 05 83 56 17 00 0f 83 91 03 00 00 48 8b 57 10 48 85 d2 0f 84 84 03 00 00 f6 c2 0f 0f 85 6f 06 00 00 64 8b 34 25 18 00 00 00 <48> 8b 42 10 85 f6 74 8f e9 c2 00 00 00 66 2e 0f 1f 84 00 00 00 00
Mar 16 15:01:00 pop-os PackageKit[1236]: resolve transaction /4741_eddabccd from uid 1000 finished with success after 260ms
Mar 16 15:01:01 pop-os systemd[2477]: app-gnome-io.elementary.appcenter\x2ddaemon-2880.scope: Consumed 39.688s CPU time.
```

I know the current version's already not entirely stable, but I wanted to mention this in case it's related to the most recent changes, since I hadn't noticed as much crashing before.

**Pull request closed without merging**
