### PR TITLE
Narrow window focal

### PR DESCRIPTION
**Pull request by isantop**
This is a new iteration of #155 with builds enabled only for focal

The Window in AppCenter was previously limited to a minimum width of about 800 pixels. This is rather wide, and prevents some corner cases while tiling. This PR solves this by reworking a lot of the design such that it shrinks elegantly to smaller sizes. It does this my removing some of the size constraints we previously had, and using technologies designed for more responsive design like LibHandy (HdyColumn).

### CODE REVIEW

**Comment by leviport** [comment]
I found a couple of things:

1. The screenshot scaling slowness actually makes tiling look very bizarre. The video "tiling-resize-slow.mp4" in the zip file shows what it does. We probably don't want to leave it like this. If we could make it re-draw at a lower rate, I bet that would do the trick.
2. If I tile it to be a quarter of the width of my 1920x1080p display, only some pages shrink down to that width. The other video, "quarter-width-1920x1080.mp4" shows this. It's still usable at that width, but it does overlap with other windows on the right edge. It's still heaps better than some other default apps though, so I'm not sure how good is good enough, at least for the present moment.

[pop-shop-videos.zip](https://github.com/pop-os/shop/files/4331132/pop-shop-videos.zip)

**Comment by brs17** [comment]
@isantop let's get the regression resolved and solve the issues @leviport raised in separate prs. The current status (minus the regression) is a great improvement over what it had been and should be released.

**Comment by isantop** [comment]
@brs17 Does that mean you want to merge this into master and then fix the regressions in separate PRs?

**Comment by leviport** [comment]
The regression @brs17 identified needs to be fixed before merging. The things I found are not regressions, so those can be fixed in separate PRs. This is a huge improvement, so we want to get it merged.

**Comment by isantop** [comment]
@brs17 I believe that regression has been fixed as of 
7f00335

**Pull request merged**
