### PR TITLE
fix: Allow update notifications to open installed view

### PR DESCRIPTION
**Pull request by mmstick**
After installing this update, it's necessary to restart the appcenter in `--silent` mode to get the DBus service running. Then, subsequent `io.elementary.appcenter --show-updates` commands will show the installed view, and `io.elementary.appcenter` will show the default home view.

### CODE REVIEW

**Comment by n3m0-22** [comment]
Tested on 21.10 and 22.04. On both, before installing this `io.elementary.appcenter --show-updates` and `io.elementary.appcenter` both opened pop-shop to home view. After `io.elementary.appcenter --show-updates` opens to installed view and `io.elementary.appcenter` opens to home view. 

Note: I could not test clicking on a notification. Both systems have updates to be installed and both show a badge count on the pop-shop icon, but neither one ever shows an update notification. I checked without this installed and still no update notifications. I have Automatic Updates turned off and Show Update Notifications set to Daily. Running `apt list--upgradable` shows several packages ready for update. 

If all of that is ok, and does not affect this update then it is ready for approval. Otherwise it needs more testing.

**Comment by jacobgkau** [comment]
Notifications are showing up fine, but if the AppCenter wasn't already running, then clicking the notification doesn't open the AppCenter properly. I get this output in the log:

```
Apr 29 08:58:07 pop-os pop-system-updater[5416]:  INFO pop_system_updater::service::session: displaying notification of available updates
Apr 29 08:58:10 pop-os pop-system-updater[6882]: connecting to client to show updates
Apr 29 08:58:10 pop-os pop-system-updater[6882]: Failed to show updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.appcenter was not provided by any .service files
Apr 29 08:58:10 pop-os io.elementary.a[6882]: Found icon of unknown type 'unknown' in 'user/flatpak/flathub/cc.nift.nsm/*', skipping it.
Apr 29 08:58:10 pop-os io.elementary.a[6882]: Found icon of unknown type 'unknown' in 'user/flatpak/flathub/cc.nift.nsm/*', skipping it.
```

And `ps aux | grep io.elem` shows the AppCenter process was started with `-u` instead of `-s`.

This should be helped by https://github.com/pop-os/shop/pull/349 (this branch is out-of-date and does not include that merged PR), but should system-updater be checking if the service is available and launching with `-s` prior to the `-u` if not?

**Comment by mmstick** [comment]
Perhaps it should. I'll open a PR for that

**Review by jacobgkau — APPROVED** [review]
This is working as expected alongside https://github.com/pop-os/system-updater/pull/9. Notifications always open the AppCenter to the Installed page. Launching with `io.elementary.appcenter` when it's already running, or clicking the icon, launches to the Home page.

If I preempt the Pop!_Shop's own autostart by running with `io.elementary.appcenter`, then click the notification, the shop is closed and re-opened to the Installed page (as pop-system-updater restarts the Pop!_Shop in `--silent` mode.)

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
