### PR TITLE
Pop!_Picks

### PR DESCRIPTION
**Pull request by cassidyjames**
Sets Pop!_Shop up as a a client for the Pop! Houston server ([Deckard](https://github.com/pop-os/deckard)), and simplifies the homepage to just be the banner, a "featured" collection of up to 15 "Pop!_Picks", and the categories.

Before merging, we will need to:
- [ ] Get an approved list of featured apps for Deckard,
- [x] Host Deckard somewhere public, and
- [x] Change the `HOUSTON_API_URL` to our public Deckard server

image

To test, run Deckard locally like in its README, or get someone on your network to do so, and change `HOUSTON_API_URL` to the correct IP address/port combo.

### CODE REVIEW

**Comment by cassidyjames** [comment]
Cleaned up margin consistency a lot, meaning things now line up nicely!

screenshot from 2018-04-13 11-10-44

**Comment by cassidyjames** [comment]
The work here is done, now it's just a timing thing to merge in after we've gotten the approved apps for Deckard. Alternatively, we can remove any apps from Deckard and merge this in sooner. Thoughts @jackpot51 @WatchMkr @btkostner?

**Comment by jackpot51** [comment]
The list in Deckard already is pretty good. Could we make it good enough for release soon?

**Comment by cassidyjames** [comment]
@WatchMkr wants to make sure the apps have good appstream data (most do not), have been tested, and any missing ones we want to include are packaged in our PPA.

We blanked the list out now since they were just preliminary picks. That way we can manage that list separately later, but merge this sooner.

**Comment by cassidyjames** [comment]
@jackpot51 the update to blank the list out has been deployed if you want to test that id doesn't do anything negative. The Pop!_Picks just don't show up since there's nothing to show.

**Comment by jackpot51** [comment]
Ok, will try

**Comment by jackpot51** [comment]
Looks good

**Pull request merged**
