### PR TITLE
Rebase on upstream version 7.4.0

### LINKED ISSUE #233: Application list doesn't load more results if the window is taller than the list
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
pop-shop
`3.3.0pop0~1600965555~20.10~f37e26a`

**Issue/Bug Description:**
Opening any of the category app lists or when searching in the searchbox the app list view it loads 21 apps but on screens where the window is tall enough that the bottom of the list is inside  the height of the window the pagination doesn't work so you can't see more than those 21 results. 
A screenshot hopefully makes more sense: 

pop_shop-list-length

**Steps to reproduce (if you know):**
Open a pop-shop category in a tall window

**Expected behavior:**
It loads enough apps to fill the height of the window and pagination works as expected so all apps can be viewed

**Other Notes:**

### PR DESCRIPTION
**Pull request by jacobgkau**
This rebases on upstream tag [7.4.0](https://github.com/elementary/appcenter/tree/7.4.0), which is currently the latest tag. This may be the last rebase (especially if we switch over to cosmic-store with Epoch), as upstream has started removing .deb functionality from the app since this tag (they're separating out "OS updates" into a separate app, and using AppCenter only for Flatpaks).

This needs a @pop-os/ux sign-off because the Installed page has switched from a list view to a grid view for installed apps (it still uses a list for available updates). Upstream's [rationale](https://github.com/elementary/appcenter/pull/1974) seems to have been that it simply wastes less space and requires less scrolling:

Screenshot from 2024-03-05 09-31-58

Screenshot from 2024-03-05 09-31-43

Screenshot from 2024-03-05 09-31-47

Aside from that UX change, this PR fixes #233 for the list view in search results. I've tested and confirmed this with a tall window layout on a vertical display. Knocking that issue out is the primary benefit of this rebase.

This PR also fixes persistent highlights on the grid view items of the Recently Updated and Category sections on the homepage, as well as apps within category pages-- the blue highlights in the below screenshot (from 7.3.0) will **no longer occur** after selecting an item and then going back (this would be relatively easy to apply as a patch to 7.3.0, if we decided to scrap the rebase):

screenshot-2024-03-05-16-37-03

I've tested that the following is still working:

- [X] Installing, opening, and removing a .deb app.
- [X] Installing, opening, and removing a Flatpak app.
- [X] Installing mixed .deb/Flatpak updates.
- [X] The menu items and keyboard shortcuts for the following still work:
    - [X] Installed page
    - [X] Automatic Update settings
    - [X] Repoman
    - [X] Refreshing the cache (updating repos)

### CODE REVIEW

**Comment by jacobgkau** [comment]
Since this is merging into `master_jammy`, only the Jammy builds need to work, so it's fine this is failing to build for the other releases.

Also, since this is a rebase, the conflicts are to be expected, and this will need to be force-pushed to `master_jammy` once approved.

**Review by jackpot51 — APPROVED** [review]

**Comment by maria-komarova** [comment]
It looks slightly weird visually with the list of apps requiring updates at the top and the grid below. But other than that I don't think there are any usability issues. Does it resize to a narrow window width when the grid gets to one column?

**Comment by leviport** [comment]
Yep, looks like that's working as expected:

screenshot-2024-03-06-15-46-44

**Comment by leviport** [comment]
I think the change makes the confusing Nvidia driver issue a little bit better. There's more distinction now between the list of updates and the list of installed and up-to-date applications. At the very least, it's certainly no worse than it was before.

screenshot-2024-03-06-15-48-26

**Review by maria-komarova — APPROVED** [review]

**Review by leviport — APPROVED** [review]
I messed with it some last night, and a bunch more this morning. Everything seems to be working. It seems like it's a little easier on RAM now too, which is a welcome improvement.

**Pull request merged**
