### PR TITLE
fix(css): Ensure text stays readable

### LINKED ISSUE #173: Pop Shop Install Button Can Get Into a Low Contrast State
This seems to occur with some flatpaks by clicking the area near the Install button. The screenshot has Hackgregator. Also try Rocket.chat as another example.
install_button_text

### PR DESCRIPTION
**Pull request by isantop**
This ensures that the text of the install button stays readable even if the flowboxchild with the buttons ends up selected (e.g. if it is clicked).

Fixes #173

### CODE REVIEW

**Comment by cassidyjames** [comment]
You should be able to set `selection_mode = Gtk.SelectionMode.NONE;` to prevent the flowboxchild from getting selected if it doesn't make sense to select it.

**Comment by isantop** [comment]
@cassidyjames That doesn't seem to prevent the selected classes from being applied to the FlowBoxChild widgets for some reason. I think the CSS change is the correct way to do this right now.

**Comment by jackpot51** [comment]
This doesn't need to build on pre-focal, build failures can be ignored

**Comment by leviport** [comment]
@jackpot51 I'll let you merge it since it looks like it's going into `master`. It's good on focal though.

**Pull request merged**
