### PR TITLE
Rebase w/ Flatpak Support (eoan)

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Comment by leviport** [comment]
I'm getting some interesting behavior with flatpak applications being installed alongside .deb versions of the same application. For example, if I install gnome-builder from flathub, then install the .deb version as well, I only see the flatpak version in my installed applications. If I launch `gnome-builder` in a terminal, I get the .deb version. Since I can install both, it makes me think we should make it easier to choose which one I want to launch.

**Comment by mmstick** [comment]
I wonder if this is a known issue upstream, or if it has been fixed there.

**Comment by cassidyjames** [comment]
List views will de-deplicate/group apps by their ID, and thus only show one "GNOME Builder" under "Installed". However, the app info view should still show the combobox to switch between remotes. I'll test this on elementary OS 5.1, but I don't have a disco or focal install handy to test there.

**Comment by cassidyjames** [comment]
Ah, actually in elementary OS 5.1 I see both versions under the "Installed" view.

Screenshot from 2020-01-23 11 59 45@2x

**Comment by mmstick** [comment]
Then it sounds like it's worth doing a rebase again.

Aliases solve the flatpak issue. I have

```
alias code = flatpak run com.visualstudio.code
```

in my shell initrc so that `code .` works as before.

**Comment by mmstick** [comment]
Worked, though it's strange to see "Up to 392.2 TB" of updates

Screenshot from 2020-01-23 13-16-45

I will also note that clicking on OS updates causes the appcenter to crash, though this behavior is the same as before rebasing again.

**Comment by cassidyjames** [comment]
@mmstick that size calculation is coming straight from Flatpak and is unrelated to the rebasing—the same number would be displayed on the CLI. It was a bug that was recently fixed in Flatpak itself. https://github.com/flatpak/flatpak/pull/3369

**Comment by jackpot51** [comment]
We need to add a Depends: pyflatpak for focal due to https://github.com/pop-os/repoman/pull/38

**Comment by ids1024** [comment]
Closing, since Eoan has passed it's EOL date.

**Pull request closed without merging**
