### PR TITLE
Rebase

### PR DESCRIPTION
**Pull request by ids1024**
https://github.com/pop-os/shop/pull/217 rebased again on the current code from Elementary.

A draft because it's not currently building on Focal (probably need a simple patch to build with older `libgranite`). And it could probably use a fair amount of testing.

### CODE REVIEW

**Comment by bflanagin** [comment]
Aware its still a draft, but wanted to share initial findings on 20.10

* Highlight issue found in early version still present in this version. :( 
Picture for reference. 
Screenshot from 2021-02-09 16-11-57

Tests done so far:
* Installed deb (passed)
* Install flatpak (passed)
* Added systemwide flatpak repo 
**Note:** I had to reboot after updates, system wide repo shows up after reboot, but killing all pop!_shop processes might force a reload
* Installed systemwide flatpak (passed)
* Launched app from pop!_shop (passed)
* Uninstalled deb (passed)
* Uninstalled flatpak (user) (passed)
* Uninstalled flatpak (system) (passed)
* Launched repoman from Pop!_Shop (passed)

Overall the interface seems faster, the switch between deb,flatpak(user),flatpak(system) is much more obvious which is good. Updates still install as expected. RAM useage is high for a program that sits in the background as stated it #257 so far I've been able to get it to 1.1GB. Probably an upstream issue.

**Comment by cassidyjames** [comment]
Newer Granite would likely build on Focal if that's simpler than reverting/patching things., but I think the other issue for Focal will be the LibHandy dep (for swipable screenshots and HdyWindow); I don't think 1.0 was ever built for Focal, and it might rely on newer GTK API.

**Comment by ids1024** [comment]
>  I don't think 1.0 was ever built for Focal, and it might rely on newer GTK API.

We already have a package for that in the Pop repos for the Gnome Control Center fork we're shipping on Focal.

Looking at the few build errors it's producing, I think it would be fairly easy to patch, but backporting `libgranite` as well is also an option.

**Comment by ids1024** [comment]
This is building on Focal now, so it should be ready for more thorough testing.

**Comment by jackpot51** [comment]
@ids1024 it would be good to include a comparison link between this branch and the upstream commit you are rebasing on

**Comment by ids1024** [comment]
Good point: https://github.com/elementary/appcenter/compare/master...pop-os:pop-shop-rebase

**Comment by bflanagin** [comment]
On first run, both in focal and groovy, the progress bar failed to appear when installing an application. However I have not been able to replicate the issue yet. On both systems the loading indicator was showing some sort of background process running. They could be connected.

**Comment by bflanagin** [comment]
There is an issue with the peek deb package where it fails to uninstall. This issue is in both focal and groovy. 
Picture for reference: 

Screenshot from 2021-02-10 16-59-15

**Comment by bflanagin** [comment]
When installing a system-wide flatpak the search shows that the application isn't installed when returning to the search list. However, removing and re-entering the search query updates the list and shows its installed. If you are installing the flatpak as a user the interface updates as expected. 

System-wide flatpaks are new and can't be tested in older versions.

**Comment by bflanagin** [comment]
Similar to the bug above, the progress bar that shows the application being installed in the search list doesn't appear when installing a system-wide flatpak.

**Comment by bflanagin** [comment]
Shell Activities integration works as expected,
Updates trigger notification event
Clicking on notification event works as expected.

**Comment by bflanagin** [comment]
## Tests passing

* Highlight issue found in early version still present in this version. :( 
Picture for reference. 
Screenshot from 2021-02-09 16-11-57

Tests done so far:
* Installed deb (passed)
* Install flatpak (passed)
* Added systemwide flatpak repo 
**Note:** I had to reboot after updates, system wide repo shows up after reboot, but killing all pop!_shop processes might force a reload
* Installed systemwide flatpak (passed)
* Launched app from pop!_shop (passed)
* Uninstalled deb (passed)
* Uninstalled flatpak (user) (passed)
* Uninstalled flatpak (system) (passed)
* Launched repoman from Pop!_Shop (passed)

Overall the interface seems faster, the switch between deb,flatpak(user),flatpak(system) is much more obvious which is good. Updates still install as expected. RAM useage is high for a program that sits in the background as stated it #257 so far I've been able to get it to 1.1GB. Probably an upstream issue.

**Comment by bflanagin** [comment]
## Bugs and Regressions

* Highlight issue found in early version still present in this version. :( 
Picture for reference. 
Screenshot from 2021-02-09 16-11-57

**Comment by ids1024** [comment]
> Using the back button from application information to category fails to "go back." Not found in previous version. Video for reference.

This seems to be an upstream issue: https://github.com/elementary/appcenter/issues/1478 (not that this affects it's significance as a bug)

> There is an issue with the peek deb package where it fails to uninstall.

Strange. I see the same thing installing and uninstalling Peak, though I haven't thoroughly tested with other packages. I don't see anything in our diff against upstream that seems relevant.

Continuing to look into the other issues.

**Comment by ids1024** [comment]
Not sure quite what's going on with the `peek` package. The issue occurs in upstream appcenter (running on Pop!_OS 20.10). Reverting to a commit older than https://github.com/pop-os/shop/commit/e22e1c1341c26b71f210fa2e91da4fc99017e73a makes it possible to uninstall, but that may not be the root of the issue.

The origin seems to be listed incorrectly:

Screenshot from 2021-02-11 15-03-41

```
> apt policy peek
peek:
  Installed: 1.5.1-1
  Candidate: 1.5.1-1
  Version table:
 *** 1.5.1-1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
        100 /var/lib/dpkg/status
```

I believe since it's from the Ubuntu repository, it should say `Ubuntu (deb)`, rather than `Pop!_OS (deb)`, as other software does. I'm not sure quite what's going on here.

**Comment by ids1024** [comment]
Okay, the origin is listed correctly if I remove the `appstream-data-pop` package, though it still shows the same error on uninstall.

https://github.com/pop-os/appstream-data/blob/master/src/data/com.uploadedlobster.peek.yml

**Comment by bflanagin** [comment]
There is one more small visual bug that I've had a hard time catching on video or in an image. On some packages when the button transitions from install to open. I get a glimpse of what might be a price? It's very quick and inconsistent.  Maybe a hold over from the elementary payment system?

**Comment by ids1024** [comment]
> Maybe a hold over from the elementary payment system?

Probably. It should be possible to remove the widget responsible for that or make sure it's never set visible. Do you have an example of a package where that appears, since you said it seems to only be for some packages?

**Comment by bflanagin** [comment]
When installing the telegram flatpak (system-wide) there is a split second during the slide in animation for the open,uninstall buttons that doesn't look like it says "install" but its quick. The issue is more obvious when there is no open button offered when the transition happens. I imagine it wasn't noticeable in older version given the lack of animation. 

Still the animation is fast enough that what I think I'm seeing might not be what I'm seeing.

**Comment by bflanagin** [comment]
As of this morning and after the update to pop!_shop I'm getting this message in the terminal.

```
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

As mentioned earlier, when installing a deb the progress bar isn't appearing in the UI, 
Debug output:
```
(io.elementary.appcenter:43090): Gtk-WARNING **: 12:01:43.255: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 17
```
Issue does not affect flatpak installs. Image for reference:

Screenshot from 2021-02-15 12-01-03

**Comment by bflanagin** [comment]
All general tests are passing. However, there is one regression in version 97bbc6e. It is similar to a closed issue we saw earlier and referenced here: https://github.com/elementary/appcenter/issues/1478. However, now instead of being triggered by going to any application it only happens after you install or uninstall an application and only in certain circumstances.

The next issue is some what exciting because I couldn't catch it last time, but the cost for an item actually appeared when installing a Debian file. (Its fast, in the video, but its obvious when you are using the app.)

I've caught both issues in the video below.

Peek 2021-03-15 09-41

**Comment by jackpot51** [comment]
I don't see the right icon when this is installed, instead I see this:
pop-shop-icon

**Comment by ids1024** [comment]
I should probably add a note here since I didn't comment about it here earlier: the progress bar not showing up properly is due to the call to `package.get_version ();` added to `AppInfoView` in our patches. That calls `populate_backend_details_sync` which spawns a `MainLoop` to call the async function `backend.get_package_details`. Not sure if the problem is just the the amount of time that takes, or if the recursive mainloop result in some funny behavior.

Don't know how to fix that, though reverting that Pop!_OS modification and not calling that function there would obviously fix it.

**Comment by ids1024** [comment]
Applying the change adding the `package.get_version()` call to older Appcenter commits, it seems the progress bar issue only happens with f0af25d6ae28327fdde92fd18282a0f9d2652a25 or later. Not sure exactly why.

**Comment by ids1024** [comment]
Okay, added a commit that seems to fix the progress bar issue.

**Comment by ids1024** [comment]
The correct icon should show now, at least. There may still be more minor issue we want to fix.

**Comment by bflanagin** [comment]
The progress bar is fixed
Icon image is fixed.(kind of missing the drama of not know what icons was coming next)
No regressions found based on previous tests. 

## Issues to consider.
* No search results using activities search. (should the be a separate PR?)

**Comment by ids1024** [comment]
>No search results using activities search. (should the be a separate PR?)

That was due to https://github.com/pop-os/shop/pull/264, right? That merged into `pop-shop-rebase`, so it's is a regression relative to the currently released version. Not sure exactly what we want to do about that.

**Comment by bflanagin** [comment]
Sorry @ids1024 I didn't get the alert from your comment. Yes I failed to notice (its not a part of my workflow) the issue when I approved the ram usage fix.  I believe when the issue first came up Jeremy suggested using `io.elementary.appcenter -s` when needed and, I guess, killing the process after a certain timeout? Would it be possible to create a service that watches for Activities to  launch, execute pop_shop in background mode, then kill it after 15 or so seconds once Activities is close? Beyond that I think its as good as its going to get unless there are any major changes upstream.

**Comment by ids1024** [comment]
> Would it be possible to create a service that watches for Activities to launch, execute pop_shop in background mode, then kill it after 15 or so seconds once Activities is close?

Dbus-daemon actually has support for starting a systemd service when a certain name is accessed on dbus. It may work well here, though I don't think it's typical to stop the daemon after a timeout.

**Comment by bflanagin** [comment]
I believe its the daemon that is eating all the ram which led to #264 as a workaround. I'd hate to see the savings be wasted the first time someone uses Activities.

**Comment by ids1024** [comment]
I've reverted https://github.com/pop-os/shop/pull/264 for now, as discussed at meeting. Hopefully we can fix that or find a better solution in the future.

Hopefully this is ready to be merged now. Waiting on engineering review and approval from QA.

**Comment by bflanagin** [comment]
Activities search is working again, all previous checks working as previously reported.

**Review by bflanagin — APPROVED** [review]

**Review by jackpot51 — APPROVED** [review]

**Comment by jackpot51** [comment]
@ids1024 feel free to reset master to this, looks good to me

**Comment by ids1024** [comment]
I've deleted `master_hirsute` and force pushed this version to `master`.

**Pull request closed without merging**
