### PR TITLE
Fix lack of update notifications

### PR DESCRIPTION
**Pull request by mmstick**
The appcenter was also not checking for updates periodically. It would only check for updates when a package is installed / removed.

### CODE REVIEW

**Comment by mmstick** [comment]
Looking into this. I suppose there's another area where the update count is being calculated.

**Comment by WatchMkr** [comment]
I do not think the update count is a bug. It is correct as is.

**Comment by brs17** [comment]
@WatchMkr Then should this pr not be merged at all?

**Comment by mmstick** [comment]
I think it's just odd to see `2 updates` when there's actually 47 packages being updated.

**Comment by WatchMkr** [comment]
The OS updates together as a single item (1 update) with multiple components under it. We happen to list them individually under the OS update for convenience.

Let's get "Fix lack of update notifications" in. "Display the correct update count" is not a bug.

**Pull request merged**
