### PR TITLE
New height

### PR DESCRIPTION
**Pull request by cassidyjames**
To fit the picks and some categories. Up for discussion.

### CODE REVIEW

**Comment by brs17** [comment]
On a hidpi screen:

**Before:**

screenshot from 2018-08-23 16-12-01
screenshot from 2018-08-23 16-39-52

**After:**


screenshot from 2018-08-23 16-15-59
screenshot from 2018-08-23 16-16-25

**Comment by brs17** [comment]
On a hidpi display it just seems to fit most of the pics but nothing else. I am not sure this really solves the problem you are looking to solve.

Is the problem that we want to show that "Categories" do exist on that page?

**Comment by cassidyjames** [comment]
@brs17 yeah I think when I set that height, there were fewer picks. So the idea was to show the picks and some of the top of categories, so users know they're there. But with the current amount of space the picks take up, I'm not sure that it's really necessary.

**Comment by brs17** [comment]
Just throwing an idea out there, perhaps a scrolling mechanism of some sort for the Pop!_pics, to limit the pics to one(maybe 2) row(s), might make more sense? 

Perhaps @cassidyjames, create an issue for the problem you are looking to solve and we can have an implementation discussion there. Regardless, I am going to close this pr because a solution to the problem has not yet been decided.

**Pull request closed without merging**
