### PR TITLE
Make Package-Finding Operations Async

### LINKED ISSUE #94: Hangs/Freezes when installing multiple programs and examining installed codecs
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Commit: 7c64f3f553a6b5baa078f272631d09abb3d5a222

**Issue/Bug Description:**

When  installing two applications at the "same time" and then selecting a  codec that is already installed. Pop!_Shop freezes. I notice with or  without the pr (https://github.com/pop-os/shop/pull/91), selecting a codec seems to take longer to load than viewing other applications already installed.

So I was able to grab the journald logs from when Pop!_Shop freezes.
[ui-freezes.log](https://github.com/pop-os/shop/files/2354423/ui-freezes.log)

I saw once when recreating this freeze that it did not freeze but just took a little bit to open the codec page (longer than when I wasn't installing at the same time). Logs for this are here:

[longtime-nofreeze.log](https://github.com/pop-os/shop/files/2354424/longtime-nofreeze.log)

**Steps to reproduce (if you know):**
1. Select on a category.
2. Quickly install two different programs.
3. While these programs are installing, go over to the `Installed` tab.
4. Scroll down and select an installed codec (I selected on one of the GStreamer Codecs).
5. Pop!_Shop will (often) freeze at this point.

**Other Notes:**

This issue was initially discovered when reviewing this pr: https://github.com/pop-os/shop/pull/91 . It was decided that the pr made enough progress/improvements that this bug could be introduced and dealt with at a later point in time.

### PR DESCRIPTION
**Pull request by mmstick**
@brs17 This seems to fix the issue where opening a codec package causes the UI to freeze.

Fixes #94 

Upstream PR https://github.com/elementary/appcenter/pull/805

### CODE REVIEW

**Comment by brs17** [comment]
Looks like upstream has requested some changes, and perhaps it is just about ready to be signed off on, so maybe we try and get that merged and then pull in their changes?

**Comment by brs17** [comment]
For what it's worth though, works like a charm! (fixes the issue it says it does)

**Comment by brs17** [comment]
Looks like it has been approved upstream we should just do a sync with upstream in a bit!

**Comment by mmstick** [comment]
This is included within https://github.com/pop-os/shop/pull/103

**Pull request closed without merging**
