### PR TITLE
Open gnome-control-center for network settings.

### PR DESCRIPTION
**Pull request by jackpot51**
This launches gnome control center's network page when clicking on network settings. Fixes https://github.com/pop-os/shop/issues/29

This also marks debian/rules as executable, a simple operation to make it easier to use sbuild.

### CODE REVIEW

**Comment by jackpot51** [comment]
For @isantop, please review the code
For @brs17, please attempt to run this version with the network disconnected. Clicking on the Network Settings button should launch gnome control center.

**Comment by jackpot51** [comment]
I agree. It appears, however, to only be a standard with Switchboard. I have not seen standardization or utilization of `settings://` outside of Elementary OS.

**Comment by isantop** [comment]
@cassidyjames knows of a few, apparently in xfce as an example

**Comment by jackpot51** [comment]
I tested this on my system @isantop @brs17, and it appears to work. I will merge.

**Pull request merged**
