### PR TITLE
fix screenshot scaling

### PR DESCRIPTION
**Pull request by 13r0ck**

### CODE REVIEW

**Review by jacobgkau — COMMENTED** [review]
This works great to get rid of the small screenshot bug, and seems to also make screenshot loading a little faster. It does make screenshots appear off-center, though. Here's a multi-screenshot app and a single-screenshot app before:

Screenshot from 2022-03-16 09-53-39

Screenshot from 2022-03-16 09-53-51

After:

Screenshot from 2022-03-16 09-49-56

Screenshot from 2022-03-16 09-50-10

For the multi-screenshot app, it starts slightly more centered (like how the single-screenshot app looks), but loses all of its left padding when the window loses focus.

**Comment by 13r0ck** [comment]
Oh I missed that. I will get that fixed.

**Comment by 13r0ck** [comment]
@jacobgkau that should be better now

**Review by jacobgkau — APPROVED** [review]
Screenshots are now centered again. This still conclusively fixes the screenshot sizing bug.

I think this could probably be merged since `upstream-rebase` is a dev branch, but if you want to get an engineering review first, that's fine too.

**Comment by 13r0ck** [comment]
Thanks! I need @isantop to merge this, as upstream-rebase is his branch

**Review by isantop — CHANGES_REQUESTED** [review]
With this patch, the screenshots no longer scale at all to narrow widths. Since this is one of the features explicitly missing from the current master, this will need to be fixed. 

image

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
On [d14faaf](https://github.com/pop-os/shop/pull/336/commits/d14faaf32fdd59efafe63883e558f9c5efa918dd), it seems like the margin around the screenshot has increased a lot. On multi-screenshot apps, the next/previous screenshots are cut off, which makes this look unintentional.

Screenshot from 2022-03-22 15-34-11

**Comment by 13r0ck** [comment]
@jacobgkau strangely I am not seeing that on my gaze16. Does [d6c2c24](https://github.com/pop-os/shop/pull/336/commits/d6c2c2451cc27ebda97a6014a168e919d413075c) fix it? If not, what system are you on?

**Comment by jacobgkau** [comment]
> @jacobgkau strangely I am not seeing that on a gaze16. Does [d6c2c24](https://github.com/pop-os/shop/pull/336/commits/d6c2c2451cc27ebda97a6014a168e919d413075c) fix it? If not, what system are you on?

Ah, looks like it's happening on addw2 (still happening on d6c2c24) but not on oryp7. Can you take a look on a HiDPI system?

**Comment by 13r0ck** [comment]
@jacobgkau 
[6a627fd](https://github.com/pop-os/shop/pull/336/commits/6a627fdf77b93919eb2e6b5ab89dc698c5707a93) should fix the hidpi scaling. Thank you for finding that!

**Comment by jacobgkau** [comment]
That issue is fixed on [6a627fd](https://github.com/pop-os/shop/pull/336/commits/6a627fdf77b93919eb2e6b5ab89dc698c5707a93), and both display and resize/scaling are working on LoDPI and HiDPI, but I am seeing the Pop!_Shop use a lot of CPU and noticeably lag when trying to resize the window now. I can sometimes see the screenshot visibly flickering in and out of existence as I resize the window.

https://user-images.githubusercontent.com/7199422/160017968-8e0063cc-b127-49d2-9ad3-6e79c83ffa8a.mp4

**Comment by 13r0ck** [comment]
I added some rate limiting to the scaling. That improved performance for me. How does that look for you?

The flickering is unfortunately a side effect of re-drawing the images while resizing the window.

**Comment by jacobgkau** [comment]
The responsiveness is better (if not perfect), but the flickering is still occurring.

> The flickering is unfortunately a side effect of re-drawing the images while resizing the window.

I'm sure you meant something more specific technically, but there must be other ways to scale an image while resizing a window since the current `upstream-rebase` branch is able to resize the image without flickering (and I can resize an Image Viewer window without the image flickering, etc.)

This is resizing on `upstream-rebase`:

https://user-images.githubusercontent.com/7199422/160169556-fd27149b-1814-4bde-8acb-124350c866f5.mp4

This is resizing on `upstream-rebase-fix-screenshots`; even activating or deactivating the scrollbar causes the image to flicker (which is weird, since the scrollbar is an overlay and shouldn't actually be resizing the image, to my understanding):

https://user-images.githubusercontent.com/7199422/160169561-f4bea953-2b25-45da-95b3-8390b75da8ae.mp4

**Comment by 13r0ck** [comment]
> This is resizing on upstream-rebase-fix-screenshots; even activating or deactivating the scrollbar causes the image to flicker (which is weird, since the scrollbar is an overlay and shouldn't actually be resizing the image, to my understanding):

Hmm I'm probably listening to events from the wrong widget. I should be able to fix that

**Comment by leviport** [comment]
I've had the reason for flickering while resizing explained to me, and I think we should consider it non-blocking. It's definitely not great, but the clamp thing that allows it to resize nicely in the upstream rebase branch is what's responsible for the scaling bug. This fix bypasses the clamp thing and makes it so dragging deletes the screenshot and redraws it in the correct size. 

Flickering while hovering over the scroll bar, however, is definitely something I'd like to see fixed before merging.

**Comment by 13r0ck** [comment]
[f9faaa1](https://github.com/pop-os/shop/pull/336/commits/f9faaa1645da1078368f0066468194ed5aa5613a) fixes the flickering when hovering over the scroll bar. It improves on the flickering when scaling, rather than a constant strobe the screenshots hide until resizing is finished.

But...

This shouldn't be approved, it doesn't work. Not just because of the most recent commit, all of my commits that attempt to remove an redraw the screenshots don't work

Steps to reproduce:
1. scroll screenshot carousel.
2. Screenshots will stop scaling

:disappointed:

**Comment by 13r0ck** [comment]
@jacobgkau this is ready for QA again.

Thank you @isantop for helping find a solution to that last bug

**Review by isantop — APPROVED** [review]
I don't like that the screenshots don't resize in real-time with this patch, but I think this is a good solution until we have a GTK4 port with Gtk.Picture

**Review by jacobgkau — APPROVED** [review]
Yeah, this is not ideal, but if it's the best we can do, it's more acceptable than the bug this PR is fixing.

https://user-images.githubusercontent.com/7199422/160660646-c4c5fbba-c618-43dd-959a-d333d7daaaba.mp4

The scrollbar doesn't cause the screenshot to hide, only resizing does. Looks the same on HiDPI.

**Pull request merged**
